services:
  mysql:
    image: mysql:8.4
    container_name: mysql_server

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: CSDL_VIEN_CHUC

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD} && test ! -f /var/lib/mysql/.entrypoint-locking-file"]
      interval: 5s
      timeout: 5s
      retries: 20

      
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./DB/01_DB_innit.sql:/docker-entrypoint-initdb.d/01_DB_innit.sql
      - ./DB/03_DB_vienchuc_edit_SP.sql:/docker-entrypoint-initdb.d/03_DB_vienchuc_edit_SP.sql
      - ./DB/02_DB_views.sql:/docker-entrypoint-initdb.d/02_DB_views.sql
      - ./DB/04_DB_Thongke_view.sql:/docker-entrypoint-initdb.d/04_DB_Thongke_view.sql
      - ./DB/05_HR_procedure.sql:/docker-entrypoint-initdb.d/05_HR_procedure.sql
      - ./DB/06_VienChuc_procedure.sql:/docker-entrypoint-initdb.d/06_VienChuc_Procedure.sql
      - ./DB/07_DB_triggers.sql:/docker-entrypoint-initdb.d/07_DB_triggers.sql
      - ./DB/08_DB_roles.sql:/docker-entrypoint-initdb.d/08_DB_roles.sql

    ports:
      - "${MYSQL_PORT}:3306"

    networks:
      - mysql_network

  php:
    build: .
    container_name: php_server

    volumes:
      - ./src:/var/www/html

    ports:
      - "${PHP_PORT}:80"

    depends_on:
      - mysql

    networks:
      - mysql_network

  importer:
    build: .
    container_name: php_importer

    volumes:
      - ./src:/var/www/html

    command: >
      sh -c "
        sleep 10 &&
        php /var/www/html/Data/importdata.php;
        tail -f /dev/null
      "

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - mysql_network
volumes:
  mysql_volume:

networks:
  mysql_network: