services:
  mysql:
    image: mysql:8.4
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./DB/DB_innit.sql:/docker-entrypoint-initdb.d/DB_innit.sql
    ports:
      - 3307:3306
    networks:
      - mysql_network

volumes:
  mysql_volume:

networks:
  mysql_network: