services:
  mysql:
    image: mysql:8.4
    container_name: mysql_server

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: CSDL_VIEN_CHUC

    volumes:
      - mysql_volume:/var/lib/mysql
      - ./DB/DB_innit.sql:/docker-entrypoint-initdb.d/DB_innit.sql
      - ./DB/DB_views.sql:/docker-entrypoint-initdb.d/DB_views.sql
      - ./DB/HR_procedure.sql:/docker-entrypoint-initdb.d/HR_procedure.sql
      - ./DB/DB_triggers.sql:/docker-entrypoint-initdb.d/DB_triggers.sql
      - ./DB/DB_roles.sql:/docker-entrypoint-initdb.d/DB_roles.sql

    ports:
      - "${MYSQL_PORT}:3306"

    networks:
      - mysql_network

  php:
    build: .
    container_name: php_server

    volumes:
      - ./src:/var/www/html

    ports:
      - "${PHP_PORT}:80"

    depends_on:
      - mysql

    networks:
      - mysql_network

  importer:
    build: .
    container_name: php_importer

    volumes:
      - ./src:/var/www/html

    command: >
      sh -c "
        sleep 20 &&
        php /var/www/html/Data/importdata.php;
        tail -f /dev/null
      "

    depends_on:
      - mysql

    networks:
      - mysql_network
volumes:
  mysql_volume:

networks:
  mysql_network: