/*==============================================================*/
/* DBMS name:      MySQL                                        */
/* Optimized for universal MySQL compatibility                  */
/*==============================================================*/

SET FOREIGN_KEY_CHECKS = 0;
SET GLOBAL activate_all_roles_on_login = ON;

CREATE DATABASE IF NOT EXISTS CSDL_VIEN_CHUC;
USE CSDL_VIEN_CHUC;

-- -----------------------------------------------------
-- DROP EXISTING TABLES (Automatically drops associated indexes)
-- -----------------------------------------------------

DROP TABLE IF EXISTS BI_KYLUAT;
DROP TABLE IF EXISTS BACLUONG;
DROP TABLE IF EXISTS CAPLYLUANCHINHTRI;
DROP TABLE IF EXISTS CAPQUANLYNHANUOC;
DROP TABLE IF EXISTS CHITIETLUONG;
DROP TABLE IF EXISTS CHUCDANH_NGHENGHIEP;
DROP TABLE IF EXISTS CHUCVU;
DROP TABLE IF EXISTS CHUNGCHITINHOC;
DROP TABLE IF EXISTS CHUYENMON;
DROP TABLE IF EXISTS COQUAN;
DROP TABLE IF EXISTS CO_CAPLYLUANCHINHTRI;
DROP TABLE IF EXISTS CO_CAPQUANLYNHANUOC;
DROP TABLE IF EXISTS CO_CHUCVU;
DROP TABLE IF EXISTS CO_HESOLUONG;
DROP TABLE IF EXISTS CO_HOKHAUTHUONGTRU;
DROP TABLE IF EXISTS CO_TAMTRU;
DROP TABLE IF EXISTS CO_TINHTRANGSK;
DROP TABLE IF EXISTS CO_TRDCM_CAONHAT;
DROP TABLE IF EXISTS CO_TRD_NGOAINGU;
DROP TABLE IF EXISTS CO_TRD_TINHOC;
DROP TABLE IF EXISTS DANHHIEU;
DROP TABLE IF EXISTS DANTOC;
DROP TABLE IF EXISTS DUOC_KHENTHUONG;
DROP TABLE IF EXISTS HANGTHUONGBINH;
DROP TABLE IF EXISTS HINHTHUCKHENTHUONG;
DROP TABLE IF EXISTS HINHTHUCKYLUAT;
DROP TABLE IF EXISTS HOCHAM;
DROP TABLE IF EXISTS NGOAINGU;
DROP TABLE IF EXISTS NHOMNGACH;
DROP TABLE IF EXISTS QUANHAM;
DROP TABLE IF EXISTS THONGTINQUANDOI;
DROP TABLE IF EXISTS THUOC_NHOM_NGACH;
DROP TABLE IF EXISTS THUOC_QUANDOI;
DROP TABLE IF EXISTS THUOC_TOCHUCDOANTHECHINHTRIXAHOI;
DROP TABLE IF EXISTS TINHTHANH;
DROP TABLE IF EXISTS TINHTRANGSUCKHOE;
DROP TABLE IF EXISTS TOCHUCDOANTHECHINHTRIXAHOI;
DROP TABLE IF EXISTS TONGIAO;
DROP TABLE IF EXISTS TRINHDOHOCVAN;
DROP TABLE IF EXISTS TUYENDUNG;
DROP TABLE IF EXISTS VIENCHUC;
DROP TABLE IF EXISTS XAPHUONG;


-- -----------------------------------------------------
-- TABLE CREATION
-- -----------------------------------------------------

CREATE TABLE BACLUONG (
   MABACLUONG           CHAR(5)              NOT NULL,
   CONSTRAINT PK_BACLUONG PRIMARY KEY (MABACLUONG)
);

CREATE TABLE BI_KYLUAT (
   MAHINHTHUCKYLUAT     CHAR(5)              NOT NULL,
   MAVIENCHUC           CHAR(10)             NOT NULL,
   NAMBIKYLUAT          DATETIME             NULL,
   SOQUYETDINHKYLUAT    CHAR(50)             NULL,
   NGUOIKYQUYETDINHKYLUAT CHAR(150)           NULL,
   CONSTRAINT PK_BI_KYLUAT PRIMARY KEY (MAHINHTHUCKYLUAT, MAVIENCHUC)
);

CREATE INDEX BI_KYLUAT_FK ON BI_KYLUAT (MAHINHTHUCKYLUAT ASC);
CREATE INDEX BI_KYLUAT2_FK ON BI_KYLUAT (MAVIENCHUC ASC);

CREATE TABLE CAPLYLUANCHINHTRI (
   MACAPCT              CHAR(5)              NOT NULL,
   TENCAPCT             VARCHAR(30)          NULL,
   CONSTRAINT PK_CAPLYLUANCHINHTRI PRIMARY KEY (MACAPCT)
);

CREATE TABLE CAPQUANLYNHANUOC (
   MACAPQLNN            CHAR(5)              NOT NULL,
   TENCAPQLNN           VARCHAR(30)          NULL,
   CONSTRAINT PK_CAPQUANLYNHANUOC PRIMARY KEY (MACAPQLNN)
);

CREATE TABLE CHITIETLUONG (
   MACHITIETLUONG       CHAR(5)              NOT NULL,
   CONSTRAINT PK_CHITIETLUONG PRIMARY KEY (MACHITIETLUONG)
);

CREATE TABLE CHUCDANH_NGHENGHIEP (
   MANGHENGHIEP         CHAR(5)              NOT NULL,
   TENNGHENGHIEP        VARCHAR(30)          NULL,
   CONSTRAINT PK_CHUCDANH_NGHENGHIEP PRIMARY KEY (MANGHENGHIEP)
);

CREATE TABLE CHUCVU (
   MACHUCVU             CHAR(5)              NOT NULL,
   TENCHUCVU            CHAR(30)             NULL,
   CONSTRAINT PK_CHUCVU PRIMARY KEY (MACHUCVU)
);

CREATE TABLE CHUNGCHITINHOC (
   MACHUNGCHITINHOC     CHAR(5)              NOT NULL,
   CHUNGCHITINHOC       VARCHAR(30)          NULL,
   CONSTRAINT PK_CHUNGCHITINHOC PRIMARY KEY (MACHUNGCHITINHOC)
);

CREATE TABLE CHUYENMON (
   MACHUYENMON          CHAR(5)              NOT NULL,
   TENCHUYENMON         VARCHAR(30)          NULL,
   CONSTRAINT PK_CHUYENMON PRIMARY KEY (MACHUYENMON)
);

CREATE TABLE COQUAN (
   MACOQUAN             CHAR(5)              NOT NULL,
   TENCOQUAN            VARCHAR(30)          NULL,
   CONSTRAINT PK_COQUAN PRIMARY KEY (MACOQUAN)
);

CREATE TABLE CO_CAPLYLUANCHINHTRI (
   MACAPCT              CHAR(5)              NOT NULL,
   MAVIENCHUC           CHAR(10)             NOT NULL,
   CONSTRAINT PK_CO_CAPLYLUANCHINHTRI PRIMARY KEY (MACAPCT, MAVIENCHUC)
);

CREATE INDEX CO_CAPLYLUANCHINHTRI_FK ON CO_CAPLYLUANCHINHTRI (MACAPCT ASC);
CREATE INDEX CO_CAPLYLUANCHINHTRI2_FK ON CO_CAPLYLUANCHINHTRI (MAVIENCHUC ASC);

CREATE TABLE CO_CAPQUANLYNHANUOC (
   MACAPQLNN            CHAR(5)              NOT NULL,
   MAVIENCHUC           CHAR(10)             NOT NULL,
   CONSTRAINT PK_CO_CAPQUANLYNHANUOC PRIMARY KEY (MACAPQLNN, MAVIENCHUC)
);

CREATE INDEX CO_CAPQUANLYNHANUOC_FK ON CO_CAPQUANLYNHANUOC (MACAPQLNN ASC);
CREATE INDEX CO_CAPQUANLYNHANUOC2_FK ON CO_CAPQUANLYNHANUOC (MAVIENCHUC ASC);

CREATE TABLE CO_CHUCVU (
   MAVIENCHUC           CHAR(10)             NOT NULL,
   MACHUCVU             CHAR(5)              NOT NULL,
   MACOQUAN             CHAR(5)              NOT NULL,
   MANGHENGHIEP         CHAR(5)              NOT NULL,
   THOIGIANGIUCHUCVU    DATETIME             NULL,
   THOIGIANKETTHUCCHUCVU DATETIME             NULL,
   CONSTRAINT PK_CO_CHUCVU PRIMARY KEY (MAVIENCHUC, MACHUCVU, MACOQUAN, MANGHENGHIEP)
);

CREATE INDEX CO_CHUCVU_FK ON CO_CHUCVU (MAVIENCHUC ASC);
CREATE INDEX CO_CHUCVU2_FK ON CO_CHUCVU (MACHUCVU ASC);
CREATE INDEX CO_CHUCVU3_FK ON CO_CHUCVU (MACOQUAN ASC);
CREATE INDEX CO_CHUCVU4_FK ON CO_CHUCVU (MANGHENGHIEP ASC);

CREATE TABLE CO_HESOLUONG (
   MABACLUONG           CHAR(5)              NOT NULL,
   MANHOMNGACH          CHAR(4)              NOT NULL,
   MACHITIETLUONG       CHAR(5)              NOT NULL,
   HESOLUONG            DECIMAL(5,3)         NULL,
   CONSTRAINT PK_CO_HESOLUONG PRIMARY KEY (MABACLUONG, MANHOMNGACH, MACHITIETLUONG)
);

CREATE INDEX CO_HESOLUONG_FK ON CO_HESOLUONG (MABACLUONG ASC);
CREATE INDEX CO_HESOLUONG2_FK ON CO_HESOLUONG (MANHOMNGACH ASC);
CREATE INDEX CO_HESOLUONG3_FK ON CO_HESOLUONG (MACHITIETLUONG ASC);

CREATE TABLE CO_HOKHAUTHUONGTRU (
   MAVIENCHUC           CHAR(10)             NOT NULL,
   MAXAPHUONG           CHAR(5)              NOT NULL,
   THOIGIANDANGKYHOKHAU DATETIME             NULL,
   CONSTRAINT PK_CO_HOKHAUTHUONGTRU PRIMARY KEY (MAVIENCHUC, MAXAPHUONG)
);

CREATE INDEX CO_HOKHAUTHUONGTRU_FK ON CO_HOKHAUTHUONGTRU (MAVIENCHUC ASC);
CREATE INDEX CO_HOKHAUTHUONGTRU2_FK ON CO_HOKHAUTHUONGTRU (MAXAPHUONG ASC);

CREATE TABLE CO_TAMTRU (
   MAVIENCHUC           CHAR(10)             NOT NULL,
   MAXAPHUONG           CHAR(5)              NOT NULL,
   THOIGIANDANGKYTAMTRU DATETIME             NULL,
   CONSTRAINT PK_CO_TAMTRU PRIMARY KEY (MAVIENCHUC, MAXAPHUONG)
);

CREATE INDEX CO_TAMTRU_FK ON CO_TAMTRU (MAVIENCHUC ASC);
CREATE INDEX CO_TAMTRU2_FK ON CO_TAMTRU (MAXAPHUONG ASC);

CREATE TABLE CO_TINHTRANGSK (
   MAVIENCHUC           CHAR(10)             NOT NULL,
   MASUCKHOE            CHAR(5)              NOT NULL,
   CANNANG              DECIMAL(4,2)         NULL,
   CHIEUCAO             TINYINT UNSIGNED              NULL,
   THOIGIANGHINHAN      DATETIME             NULL,
   CONSTRAINT PK_CO_TINHTRANGSK PRIMARY KEY (MAVIENCHUC, MASUCKHOE)
);

CREATE INDEX CO_TINHTRANGSK_FK ON CO_TINHTRANGSK (MAVIENCHUC ASC);
CREATE INDEX CO_TINHTRANGSK2_FK ON CO_TINHTRANGSK (MASUCKHOE ASC);

CREATE TABLE CO_TRDCM_CAONHAT (
   MACHUYENMON          CHAR(5)              NOT NULL,
   MAVIENCHUC           CHAR(10)             NOT NULL,
   CONSTRAINT PK_CO_TRDCM_CAONHAT PRIMARY KEY (MACHUYENMON, MAVIENCHUC)
);

CREATE INDEX CO_TRINHDOCHUYENMONCAONHAT_FK ON CO_TRDCM_CAONHAT (MACHUYENMON ASC);

CREATE TABLE CO_TRD_NGOAINGU (
   MANGOAINGU           CHAR(5)              NOT NULL,
   MAVIENCHUC           CHAR(10)             NOT NULL,
   CONSTRAINT PK_CO_TRD_NGOAINGU PRIMARY KEY (MANGOAINGU, MAVIENCHUC)
);

CREATE INDEX CO_TRINHDONGOAINGU_FK ON CO_TRD_NGOAINGU (MANGOAINGU ASC);

CREATE TABLE CO_TRD_TINHOC (
   MACHUNGCHITINHOC     CHAR(5)              NOT NULL,
   MAVIENCHUC           CHAR(10)             NOT NULL,
   CONSTRAINT PK_CO_TRD_TINHOC PRIMARY KEY (MACHUNGCHITINHOC, MAVIENCHUC)
);

CREATE INDEX CO_TRINHDOTINHOC_FK ON CO_TRD_TINHOC (MACHUNGCHITINHOC ASC);
                    
CREATE TABLE DANHHIEU (
   MADANHHIEU           CHAR(5)              NOT NULL,
   TENDANHHIEU          VARCHAR(30)          NULL,
   CONSTRAINT PK_DANHHIEU PRIMARY KEY (MADANHHIEU)
);

CREATE TABLE DANTOC (
   MADANTOC             CHAR(5)              NOT NULL,
   TENDANTOC            VARCHAR(30)          NULL,
   CONSTRAINT PK_DANTOC PRIMARY KEY (MADANTOC)
);

CREATE TABLE DUOC_KHENTHUONG (
   MAHINHTHUCKHENTHUONG CHAR(5)              NOT NULL,
   MAVIENCHUC           CHAR(10)             NOT NULL,
   NAMNHANKHENTHUONG    DATETIME             NULL,
   SOQUYETDINHKHENTHUONG CHAR(50)             NULL,
   NGUOIKYQUYETDINHKHENTHUONG CHAR(150)           NULL,
   CONSTRAINT PK_DUOC_KHENTHUONG PRIMARY KEY (MAHINHTHUCKHENTHUONG, MAVIENCHUC)
);

CREATE INDEX DUOC_KHENTHUONG_FK ON DUOC_KHENTHUONG (MAHINHTHUCKHENTHUONG ASC);
CREATE INDEX DUOC_KHENTHUONG2_FK ON DUOC_KHENTHUONG (MAVIENCHUC ASC);

CREATE TABLE HANGTHUONGBINH (
   MAHANGTHUONGBINH     CHAR(5)              NOT NULL,
   TENHANGTHUONGBINH    VARCHAR(30)          NULL,
   CONSTRAINT PK_HANGTHUONGBINH PRIMARY KEY (MAHANGTHUONGBINH)
);

CREATE TABLE HINHTHUCKHENTHUONG (
   MAHINHTHUCKHENTHUONG CHAR(5)              NOT NULL,
   TENHINHTHUCKHENTHUONG VARCHAR(30)          NULL,
   CONSTRAINT PK_HINHTHUCKHENTHUONG PRIMARY KEY (MAHINHTHUCKHENTHUONG)
);

CREATE TABLE HINHTHUCKYLUAT (
   MAHINHTHUCKYLUAT     CHAR(5)              NOT NULL,
   TENHINHTHUCKYLUAT    CHAR(30)             NULL,
   CONSTRAINT PK_HINHTHUCKYLUAT PRIMARY KEY (MAHINHTHUCKYLUAT)
);

CREATE TABLE HOCHAM (
   MAHOCHAM             CHAR(5)              NOT NULL,
   TENHOCHAM            VARCHAR(30)          NULL,
   CONSTRAINT PK_HOCHAM PRIMARY KEY (MAHOCHAM)
);

CREATE TABLE NGOAINGU (
   MANGOAINGU           CHAR(5)              NOT NULL,
   TENNGOAINGU          VARCHAR(30)          NULL,
   CAPDO                CHAR(5)              NULL,
   CONSTRAINT PK_NGOAINGU PRIMARY KEY (MANGOAINGU)
);

CREATE TABLE NHOMNGACH (
   MANHOMNGACH          CHAR(4)              NOT NULL,
   TENNHOMNGACH         CHAR(30)             NULL,
   CONSTRAINT PK_NHOMNGACH PRIMARY KEY (MANHOMNGACH)
);

CREATE TABLE QUANHAM (
   MAQUANHAM            CHAR(5)              NOT NULL,
   TENQUANHAM           VARCHAR(30)          NULL,
   CONSTRAINT PK_QUANHAM PRIMARY KEY (MAQUANHAM)
);

CREATE TABLE THONGTINQUANDOI (
   MATTD_QD             CHAR(5)              NOT NULL,
   CONSTRAINT PK_THONGTINQUANDOI PRIMARY KEY (MATTD_QD)
);

CREATE TABLE THUOC_NHOM_NGACH (
   MAVIENCHUC           CHAR(10)             NOT NULL,
   MACHITIETLUONG       CHAR(5)              NOT NULL,
   THOIGIANBATDAUHUONG  DATETIME             NULL,
   CONSTRAINT PK_THUOC_NHOM_NGACH PRIMARY KEY (MAVIENCHUC, MACHITIETLUONG)
);

CREATE INDEX THUOC_NHOM_NGACH_FK ON THUOC_NHOM_NGACH (MAVIENCHUC ASC);
CREATE INDEX THUOC_NHOM_NGACH2_FK ON THUOC_NHOM_NGACH (MACHITIETLUONG ASC);

CREATE TABLE THUOC_QUANDOI (
   MAVIENCHUC           CHAR(10)             NOT NULL,
   MATTD_QD             CHAR(5)              NOT NULL,
   MAQUANHAM            CHAR(5)              NOT NULL,
   NGAYNHAPNGU          DATETIME             NULL,
   NGAYXUATNGU          DATETIME             NULL,
   NOINHAPNGU           TEXT                 NULL,
   CONSTRAINT PK_THUOC_QUANDOI PRIMARY KEY (MAVIENCHUC, MATTD_QD, MAQUANHAM)
);

CREATE INDEX THUOC_QUANDOI_FK ON THUOC_QUANDOI (MAVIENCHUC ASC);
CREATE INDEX THUOC_QUANDOI2_FK ON THUOC_QUANDOI (MATTD_QD ASC);
CREATE INDEX THUOC_QUANDOI3_FK ON THUOC_QUANDOI (MAQUANHAM ASC);

CREATE TABLE THUOC_TOCHUCDOANTHECHINHTRIXAHOI (
   MAVIENCHUC           CHAR(10)             NOT NULL,
   MATOCHUCDTCTXH       CHAR(5)              NOT NULL,
   NGAYVAOTOCHUC        DATETIME             NULL,
   NGAYCHINHTHUC        DATETIME             NULL,
   NGUOIGIOITHIEU       TEXT                 NULL,
   LANVAOTOCHUC         TINYINT              NULL,
   CONSTRAINT PK_THUOC_TOCHUCDOANTHECHINHTRI PRIMARY KEY (MAVIENCHUC, MATOCHUCDTCTXH)
);

CREATE INDEX THUOC_TOCHUCDOANTHECHINHTRIXAHOI_FK ON THUOC_TOCHUCDOANTHECHINHTRIXAHOI (MAVIENCHUC ASC);
CREATE INDEX THUOC_TOCHUCDOANTHECHINHTRIXAHOI2_FK ON THUOC_TOCHUCDOANTHECHINHTRIXAHOI (MATOCHUCDTCTXH ASC);

CREATE TABLE TINHTHANH (
   MATINHTHANH          CHAR(5)              NOT NULL,
   TENTINHTHANH         VARCHAR(30)          NULL,
   CONSTRAINT PK_TINHTHANH PRIMARY KEY (MATINHTHANH)
);

CREATE TABLE TINHTRANGSUCKHOE (
   MASUCKHOE            CHAR(5)              NOT NULL,
   TINHTRANGSUCKHOE     VARCHAR(20)          NULL,
   CONSTRAINT PK_TINHTRANGSUCKHOE PRIMARY KEY (MASUCKHOE)
);

CREATE TABLE TOCHUCDOANTHECHINHTRIXAHOI (
   MATOCHUCDTCTXH       CHAR(5)              NOT NULL,
   TENTOCHUCDTCTXH      TEXT                 NULL,
   CONSTRAINT PK_TOCHUCDOANTHECHINHTRIXAHOI PRIMARY KEY (MATOCHUCDTCTXH)
);

CREATE TABLE TONGIAO (
   MATONGIAO            CHAR(5)              NOT NULL,
   TENTONGIAO           VARCHAR(30)          NULL,
   CONSTRAINT PK_TONGIAO PRIMARY KEY (MATONGIAO)
);

CREATE TABLE TRINHDOHOCVAN (
   MATRINHDO            CHAR(5)              NOT NULL,
   TRINHDOGIAODUCPHOTHONG CHAR(5)              NULL,
   TRINHDONGHIEPVUCHUYENNGANH VARCHAR(100)         NULL,
   CONSTRAINT PK_TRINHDOHOCVAN PRIMARY KEY (MATRINHDO)
);

CREATE TABLE TUYENDUNG (
   MANGHENGHIEP         CHAR(5)              NOT NULL,
   MAVIENCHUC           CHAR(10)             NOT NULL,
   MACOQUAN             CHAR(5)              NOT NULL,
   NGAYTUYENDUNG        DATETIME             NULL,
   CONSTRAINT PK_TUYENDUNG PRIMARY KEY (MANGHENGHIEP, MAVIENCHUC, MACOQUAN)
);

CREATE INDEX TUYENDUNG_FK ON TUYENDUNG (MANGHENGHIEP ASC);
CREATE INDEX TUYENDUNG2_FK ON TUYENDUNG (MAVIENCHUC ASC);
CREATE INDEX TUYENDUNG3_FK ON TUYENDUNG (MACOQUAN ASC);

CREATE TABLE VIENCHUC (
   MAVIENCHUC           CHAR(10)             NOT NULL,
   MADANHHIEU           CHAR(5)              NULL,
   MATONGIAO            CHAR(5)              NULL,
   MAHOCHAM             CHAR(5)              NULL,
   MATRINHDO            CHAR(5)              NOT NULL,
   MADANTOC             CHAR(5)              NOT NULL,
   MAHANGTHUONGBINH     CHAR(5)              NULL,
   MAXAPHUONG           CHAR(5)              NOT NULL,
   XAP_MAXAPHUONG       CHAR(5)              NOT NULL,
   HO                   VARCHAR(20)          NULL,
   TENLOT               VARCHAR(40)          NULL,
   TEN                  VARCHAR(20)          NOT NULL,
   TENKHAC              VARCHAR(100)         NULL,
   NGAYSINH             DATETIME             NOT NULL,
   GIOITINH             VARCHAR(3)           NULL,
   NGAYTUYENDUNG        DATETIME             NULL,
   SOHIEUVIENCHUC       CHAR(10)             NULL,
   ANHDAIDIEN           TEXT                 NULL,
   SOCCCD               CHAR(10)             NULL,
   NOICAPCCCD           CHAR(100)            NULL,
   NGAYCAPCCCD          DATETIME             NULL,
   SOBAOHIEM            CHAR(10)             NULL,
   NHOMMAU              CHAR(3)              NULL,
   NAMDUOCPHONGHOCHAM   DATETIME             NULL,
   NAMDUOCPHONGDANHHIEU DATETIME             NULL,
   CONSTRAINT PK_VIENCHUC PRIMARY KEY (MAVIENCHUC)
);

CREATE INDEX CO_TRINHDOHOCVAN_FK ON VIENCHUC (MATRINHDO ASC);
CREATE INDEX VIENCHUC_CO_DANTOC_FK ON VIENCHUC (MADANTOC ASC);
CREATE INDEX CO_TONGIAO_FK ON VIENCHUC (MATONGIAO ASC);
CREATE INDEX CO_NOISINH_FK ON VIENCHUC (XAP_MAXAPHUONG ASC);
CREATE INDEX CO_QUEQUAN_FK ON VIENCHUC (MAXAPHUONG ASC);
CREATE INDEX DUOCPHONG_HOCHAM_FK ON VIENCHUC (MAHOCHAM ASC);
CREATE INDEX DUOCPHONG_DANHHIEU_FK ON VIENCHUC (MADANHHIEU ASC);
CREATE INDEX CO_HANGTHUONGBINH_FK ON VIENCHUC (MAHANGTHUONGBINH ASC);

CREATE TABLE XAPHUONG (
   MAXAPHUONG           CHAR(5)              NOT NULL,
   MATINHTHANH          CHAR(5)              NOT NULL,
   TENXAPHUONG          VARCHAR(30)          NULL,
   CONSTRAINT PK_XAPHUONG PRIMARY KEY (MAXAPHUONG)
);

CREATE INDEX TRUCTHUOC_FK ON XAPHUONG (MATINHTHANH ASC);

-- tự thêm vào... không ảnh hưởng đến schema, chỉ dành cho php server
CREATE TABLE USERS (
   ID                    INT AUTO_INCREMENT     NOT NULL,
   MAVIENCHUC           CHAR(10)             NULL,
   PASSWORD              VARCHAR(255)         NOT NULL,
   ROLE                  VARCHAR(20)          NOT NULL,
   CONSTRAINT PK_USER PRIMARY KEY (ID),
   FOREIGN KEY (MAVIENCHUC) REFERENCES VIENCHUC(MAVIENCHUC));


CREATE TABLE AUDIT_LOG (
   ID BIGINT AUTO_INCREMENT PRIMARY KEY,

   TABLE_NAME VARCHAR(100),
   RECORD_ID VARCHAR(100),

   ACTION_TYPE VARCHAR(20),

   OLD_DATA JSON,
   NEW_DATA JSON,

   UPDATED_BY VARCHAR(100),

   UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);
-- -----------------------------------------------------
-- FOREIGN KEY CONSTRAINTS
-- -----------------------------------------------------

ALTER TABLE BI_KYLUAT
   ADD CONSTRAINT FK_BI_KYLUA_BI_KYLUAT_HINHTHUC FOREIGN KEY (MAHINHTHUCKYLUAT)
      REFERENCES HINHTHUCKYLUAT (MAHINHTHUCKYLUAT);

ALTER TABLE BI_KYLUAT
   ADD CONSTRAINT FK_BI_KYLUA_BI_KYLUAT_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE CO_CAPLYLUANCHINHTRI
   ADD CONSTRAINT FK_CO_CAPLY_CO_CAPLYL_CAPLYLUA FOREIGN KEY (MACAPCT)
      REFERENCES CAPLYLUANCHINHTRI (MACAPCT);

ALTER TABLE CO_CAPLYLUANCHINHTRI
   ADD CONSTRAINT FK_CO_CAPLY_CO_CAPLYL_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE CO_CAPQUANLYNHANUOC
   ADD CONSTRAINT FK_CO_CAPQU_CO_CAPQUA_CAPQUANL FOREIGN KEY (MACAPQLNN)
      REFERENCES CAPQUANLYNHANUOC (MACAPQLNN);

ALTER TABLE CO_CAPQUANLYNHANUOC
   ADD CONSTRAINT FK_CO_CAPQU_CO_CAPQUA_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE CO_CHUCVU
   ADD CONSTRAINT FK_CO_CHUCV_CO_CHUCVU_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE CO_CHUCVU
   ADD CONSTRAINT FK_CO_CHUCV_CO_CHUCVU_CHUCVU FOREIGN KEY (MACHUCVU)
      REFERENCES CHUCVU (MACHUCVU);

ALTER TABLE CO_CHUCVU
   ADD CONSTRAINT FK_CO_CHUCV_CO_CHUCVU_COQUAN FOREIGN KEY (MACOQUAN)
      REFERENCES COQUAN (MACOQUAN);

ALTER TABLE CO_CHUCVU
   ADD CONSTRAINT FK_CO_CHUCV_CO_CHUCVU_CHUCDANH FOREIGN KEY (MANGHENGHIEP)
      REFERENCES CHUCDANH_NGHENGHIEP (MANGHENGHIEP);

ALTER TABLE CO_HESOLUONG
   ADD CONSTRAINT FK_CO_HESOL_CO_HESOL_BACLUONG FOREIGN KEY (MABACLUONG)
      REFERENCES BACLUONG (MABACLUONG);

ALTER TABLE CO_HESOLUONG
   ADD CONSTRAINT FK_CO_HESOL_CO_HESOLU_NHOMNGAC FOREIGN KEY (MANHOMNGACH)
      REFERENCES NHOMNGACH (MANHOMNGACH);

ALTER TABLE CO_HESOLUONG
   ADD CONSTRAINT FK_CO_HESOL_CO_HESOLU_CHITIETL FOREIGN KEY (MACHITIETLUONG)
      REFERENCES CHITIETLUONG (MACHITIETLUONG);

ALTER TABLE CO_HOKHAUTHUONGTRU
   ADD CONSTRAINT FK_CO_HOKHA_CO_HOKHAU_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE CO_HOKHAUTHUONGTRU
   ADD CONSTRAINT FK_CO_HOKHA_CO_HOKHAU_XAPHUONG FOREIGN KEY (MAXAPHUONG)
      REFERENCES XAPHUONG (MAXAPHUONG);

ALTER TABLE CO_TAMTRU
   ADD CONSTRAINT FK_CO_TAMTR_CO_TAMTRU_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE CO_TAMTRU
   ADD CONSTRAINT FK_CO_TAMTR_CO_TAMTRU_XAPHUONG FOREIGN KEY (MAXAPHUONG)
      REFERENCES XAPHUONG (MAXAPHUONG);

ALTER TABLE CO_TINHTRANGSK
   ADD CONSTRAINT FK_CO_TINHT_CO_TINHTR_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE CO_TINHTRANGSK
   ADD CONSTRAINT FK_CO_TINHT_CO_TINHTR_TINHTRAN FOREIGN KEY (MASUCKHOE)
      REFERENCES TINHTRANGSUCKHOE (MASUCKHOE);

ALTER TABLE CO_TRDCM_CAONHAT
   ADD CONSTRAINT FK_CO_TRDCM_CO_TRDCM__CHUYENMO FOREIGN KEY (MACHUYENMON)
      REFERENCES CHUYENMON (MACHUYENMON);

ALTER TABLE CO_TRDCM_CAONHAT
   ADD CONSTRAINT FK_CO_TRDCM_CO_TRDCM__VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE CO_TRD_NGOAINGU
   ADD CONSTRAINT FK_CO_TRD_N_CO_TRD_NG_NGOAINGU FOREIGN KEY (MANGOAINGU)
      REFERENCES NGOAINGU (MANGOAINGU);

ALTER TABLE CO_TRD_NGOAINGU
   ADD CONSTRAINT FK_CO_TRD_N_CO_TRD_NG_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE CO_TRD_TINHOC
   ADD CONSTRAINT FK_CO_TRD_T_CO_TRD_TI_CHUNGCHI FOREIGN KEY (MACHUNGCHITINHOC)
      REFERENCES CHUNGCHITINHOC (MACHUNGCHITINHOC);

ALTER TABLE CO_TRD_TINHOC
   ADD CONSTRAINT FK_CO_TRD_T_CO_TRD_TI_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE DUOC_KHENTHUONG
   ADD CONSTRAINT FK_DUOC_KHE_DUOC_KHEN_HINHTHUC FOREIGN KEY (MAHINHTHUCKHENTHUONG)
      REFERENCES HINHTHUCKHENTHUONG (MAHINHTHUCKHENTHUONG);

ALTER TABLE DUOC_KHENTHUONG
   ADD CONSTRAINT FK_DUOC_KHE_DUOC_KHEN_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE THUOC_NHOM_NGACH
   ADD CONSTRAINT FK_THUOC_NH_THUOC_NHO_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE THUOC_NHOM_NGACH
   ADD CONSTRAINT FK_THUOC_NH_THUOC_NHO_CHITIETL FOREIGN KEY (MACHITIETLUONG)
      REFERENCES CHITIETLUONG (MACHITIETLUONG);

ALTER TABLE THUOC_QUANDOI
   ADD CONSTRAINT FK_THUOC_QU_THUOC_QUA_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE THUOC_QUANDOI
   ADD CONSTRAINT FK_THUOC_QU_THUOC_QUA_THONGTIN FOREIGN KEY (MATTD_QD)
      REFERENCES THONGTINQUANDOI (MATTD_QD);

ALTER TABLE THUOC_QUANDOI
   ADD CONSTRAINT FK_THUOC_QU_THUOC_QUA_QUANHAM FOREIGN KEY (MAQUANHAM)
      REFERENCES QUANHAM (MAQUANHAM);

ALTER TABLE THUOC_TOCHUCDOANTHECHINHTRIXAHOI
   ADD CONSTRAINT FK_THUOC_TO_THUOC_TOC_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE THUOC_TOCHUCDOANTHECHINHTRIXAHOI
   ADD CONSTRAINT FK_THUOC_TO_THUOC_TOC_TOCHUCDO FOREIGN KEY (MATOCHUCDTCTXH)
      REFERENCES TOCHUCDOANTHECHINHTRIXAHOI (MATOCHUCDTCTXH);

ALTER TABLE TUYENDUNG
   ADD CONSTRAINT FK_TUYENDUN_TUYENDUNG_CHUCDANH FOREIGN KEY (MANGHENGHIEP)
      REFERENCES CHUCDANH_NGHENGHIEP (MANGHENGHIEP);

ALTER TABLE TUYENDUNG
   ADD CONSTRAINT FK_TUYENDUN_TUYENDUNG_VIENCHUC FOREIGN KEY (MAVIENCHUC)
      REFERENCES VIENCHUC (MAVIENCHUC);

ALTER TABLE TUYENDUNG
   ADD CONSTRAINT FK_TUYENDUN_TUYENDUNG_COQUAN FOREIGN KEY (MACOQUAN)
      REFERENCES COQUAN (MACOQUAN);

ALTER TABLE VIENCHUC
   ADD CONSTRAINT FK_VIENCHUC_CO_HANGTH_HANGTHUO FOREIGN KEY (MAHANGTHUONGBINH)
      REFERENCES HANGTHUONGBINH (MAHANGTHUONGBINH);

ALTER TABLE VIENCHUC
   ADD CONSTRAINT FK_VIENCHUC_CO_NOISIN_XAPHUONG FOREIGN KEY (XAP_MAXAPHUONG)
      REFERENCES XAPHUONG (MAXAPHUONG);

ALTER TABLE VIENCHUC
   ADD CONSTRAINT FK_VIENCHUC_CO_QUEQUA_XAPHUONG FOREIGN KEY (MAXAPHUONG)
      REFERENCES XAPHUONG (MAXAPHUONG);

ALTER TABLE VIENCHUC
   ADD CONSTRAINT FK_VIENCHUC_CO_TONGIA_TONGIAO FOREIGN KEY (MATONGIAO)
      REFERENCES TONGIAO (MATONGIAO);

ALTER TABLE VIENCHUC
   ADD CONSTRAINT FK_VIENCHUC_CO_TRINHD_TRINHDOH FOREIGN KEY (MATRINHDO)
      REFERENCES TRINHDOHOCVAN (MATRINHDO);

ALTER TABLE VIENCHUC
   ADD CONSTRAINT FK_VIENCHUC_DUOCPHONG_DANHHIEU FOREIGN KEY (MADANHHIEU)
      REFERENCES DANHHIEU (MADANHHIEU);

ALTER TABLE VIENCHUC
   ADD CONSTRAINT FK_VIENCHUC_DUOCPHONG_HOCHAM FOREIGN KEY (MAHOCHAM)
      REFERENCES HOCHAM (MAHOCHAM);

ALTER TABLE VIENCHUC
   ADD CONSTRAINT FK_VIENCHUC_VIENCHUC__DANTOC FOREIGN KEY (MADANTOC)
      REFERENCES DANTOC (MADANTOC);

ALTER TABLE XAPHUONG
   ADD CONSTRAINT FK_XAPHUONG_TRUCTHUOC_TINHTHAN FOREIGN KEY (MATINHTHANH)
      REFERENCES TINHTHANH (MATINHTHANH);

SET FOREIGN_KEY_CHECKS = 1;
