-- this take every employee's information, EVERYONE

CREATE VIEW VW_LAY_DS_VIENCHUC AS
SELECT
    vc.MAVIENCHUC,
    CONCAT(vc.HO, ' ', vc.TENLOT, ' ', vc.TEN) AS HOTEN,
    vc.NGAYSINH,
    vc.GIOITINH,
    vc.ANHDAIDIEN,
    dt.TENDANTOC,
    tg.TENTONGIAO,

    td.TRINHDONGHIEPVUCHUYENNGANH,
    cq.TENCOQUAN,
    cv.TENCHUCVU

FROM VIENCHUC vc

LEFT JOIN DANTOC dt
    ON vc.MADANTOC = dt.MADANTOC

LEFT JOIN TONGIAO tg
    ON vc.MATONGIAO = tg.MATONGIAO

LEFT JOIN TRINHDOHOCVAN td
    ON vc.MATRINHDO = td.MATRINHDO

LEFT JOIN CO_CHUCVU ccv
    ON vc.MAVIENCHUC = ccv.MAVIENCHUC

LEFT JOIN COQUAN cq
    ON ccv.MACOQUAN = cq.MACOQUAN

LEFT JOIN CHUCVU cv
    ON ccv.MACHUCVU = cv.MACHUCVU;


-- this view is for HR to manage employee's work information
CREATE VIEW VW_DS_CONGTAC AS
SELECT
    vc.MAVIENCHUC,
    CONCAT(vc.HO, ' ', vc.TENLOT, ' ', vc.TEN) AS HOTEN,
    cq.TENCOQUAN,
    cv.TENCHUCVU,
    nn.TENNGHENGHIEP,
    ccv.THOIGIANGIUCHUCVU,
    ccv.THOIGIANKETTHUCCHUCVU
FROM CO_CHUCVU ccv
JOIN VIENCHUC vc
    ON ccv.MAVIENCHUC = vc.MAVIENCHUC
JOIN CHUCVU cv
    ON ccv.MACHUCVU = cv.MACHUCVU
JOIN COQUAN cq
    ON ccv.MACOQUAN = cq.MACOQUAN
JOIN CHUCDANH_NGHENGHIEP nn
    ON ccv.MANGHENGHIEP = nn.MANGHENGHIEP;


-- this view is for HR to manage everyone's personal information
CREATE VIEW VW_ThongKeNhanSu AS
SELECT
    cq.TENCOQUAN,
    vc.GIOITINH,
    dt.TENDANTOC,
    tg.TENTONGIAO,
    COUNT(DISTINCT vc.MAVIENCHUC) AS SOLUONGVIENCHUC
FROM VIENCHUC vc
LEFT JOIN DANTOC dt
    ON vc.MADANTOC = dt.MADANTOC
LEFT JOIN TONGIAO tg
    ON vc.MATONGIAO = tg.MATONGIAO
LEFT JOIN CO_CHUCVU ccv
    ON vc.MAVIENCHUC = ccv.MAVIENCHUC
LEFT JOIN COQUAN cq
    ON ccv.MACOQUAN = cq.MACOQUAN
GROUP BY
    cq.TENCOQUAN,
    vc.GIOITINH,
    dt.TENDANTOC,
    tg.TENTONGIAO;


--  this view is for HR to manage everyone reward information
CREATE VIEW VW_KHENTHUONG AS
SELECT
    vc.MAVIENCHUC,
    CONCAT(vc.HO, ' ', vc.TENLOT, ' ', vc.TEN) AS HOTEN,
    htkt.TENHINHTHUCKHENTHUONG AS HINHTHUC_KHENTHUONG,
    dkt.NAMNHANKHENTHUONG AS THOIGIAN,
    dkt.SOQUYETDINHKHENTHUONG AS SOQUYETDINH,
    dkt.NGUOIKYQUYETDINHKHENTHUONG AS NGUOIKY
FROM DUOC_KHENTHUONG dkt
JOIN VIENCHUC vc
    ON dkt.MAVIENCHUC = vc.MAVIENCHUC
JOIN HINHTHUCKHENTHUONG htkt
    ON dkt.MAHINHTHUCKHENTHUONG = htkt.MAHINHTHUCKHENTHUONG;

-- same as above but for discipline information
CREATE VIEW VW_KYLUAT AS
SELECT
    vc.MAVIENCHUC,
    CONCAT(vc.HO, ' ', vc.TENLOT, ' ', vc.TEN) AS HOTEN,
    htkl.TENHINHTHUCKYLUAT AS HINHTHUC_KYLUAT,
    bkl.NAMBIKYLUAT AS THOIGIAN,
    bkl.SOQUYETDINHKYLUAT AS SOQUYETDINH,
    bkl.NGUOIKYQUYETDINHKYLUAT AS NGUOIKY
FROM BI_KYLUAT bkl
JOIN VIENCHUC vc
    ON bkl.MAVIENCHUC = vc.MAVIENCHUC
JOIN HINHTHUCKYLUAT htkl
    ON bkl.MAHINHTHUCKYLUAT = htkl.MAHINHTHUCKYLUAT;
