DELIMITER $$
--      ?         Cập nhật thông tin cá nhân
CREATE PROCEDURE SP_CAPNHAT_MADANHHIEU(
IN p_MAVIENCHUC CHAR(10),
IN p_MADANHHIEU CHAR(5)
)
BEGIN
UPDATE VIENCHUC
SET MADANHHIEU = p_MADANHHIEU
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$
--     ?         Cập nhật tongiao
CREATE PROCEDURE SP_CAPNHAT_MATONGIAO(
IN p_MAVIENCHUC CHAR(10),
IN p_MATONGIAO CHAR(5)
)
BEGIN
UPDATE VIENCHUC
SET MATONGIAO = p_MATONGIAO
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$

--   ?         Cập nhật học hàm
CREATE PROCEDURE SP_CAPNHAT_MAHOCHAM(
IN p_MAVIENCHUC CHAR(10),
IN p_MAHOCHAM CHAR(5)
)
BEGIN
UPDATE VIENCHUC
SET MAHOCHAM = p_MAHOCHAM
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$
--   ?         Cập nhật học vị
CREATE PROCEDURE SP_CAPNHAT_MATRINHDO(
IN p_MAVIENCHUC CHAR(10),
IN p_MATRINHDO CHAR(5)
)
BEGIN
UPDATE VIENCHUC
SET MATRINHDO = p_MATRINHDO
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$

--   ?   Cập nhật hạng thương binh
CREATE PROCEDURE SP_CAPNHAT_MAHANGTHUONGBINH(
IN p_MAVIENCHUC CHAR(10),
IN p_MAHANGTHUONGBINH CHAR(5)
)
BEGIN
UPDATE VIENCHUC
SET MAHANGTHUONGBINH = p_MAHANGTHUONGBINH
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$

--    !  MAXAXsajkaskldlsadlksajdkjladjkla
CREATE PROCEDURE SP_CAPNHAT_MAXAPHUONG(
IN p_MAVIENCHUC CHAR(10),
IN p_MAXAPHUONG CHAR(5)
)
BEGIN
UPDATE VIENCHUC
SET MAXAPHUONG = p_MAXAPHUONG
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$
--   ?  XAP MAXAPHUONG
CREATE PROCEDURE SP_CAPNHAT_XAP_MAXAPHUONG(
IN p_MAVIENCHUC CHAR(10),
IN p_XAP_MAXAPHUONG CHAR(5)
)
BEGIN
UPDATE VIENCHUC
SET XAP_MAXAPHUONG = p_XAP_MAXAPHUONG
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$

--     ? Họ
CREATE PROCEDURE SP_CAPNHAT_HO(
IN p_MAVIENCHUC CHAR(10),
IN p_HO VARCHAR(20)
)
BEGIN
UPDATE VIENCHUC
SET HO = p_HO
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$
--       ? tten lót
CREATE PROCEDURE SP_CAPNHAT_TENLOT(
IN p_MAVIENCHUC CHAR(10),
IN p_TENLOT VARCHAR(40)
)
BEGIN
UPDATE VIENCHUC
SET TENLOT = p_TENLOT
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$
--    ? name
CREATE PROCEDURE SP_CAPNHAT_TEN(
IN p_MAVIENCHUC CHAR(10),
IN p_TEN VARCHAR(20)
)
BEGIN
UPDATE VIENCHUC
SET TEN = p_TEN
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$
--   * KONO DIO DA
CREATE PROCEDURE SP_CAPNHAT_TENKHAC(
IN p_MAVIENCHUC CHAR(10),
IN p_TENKHAC VARCHAR(100)
)
BEGIN
UPDATE VIENCHUC
SET TENKHAC = p_TENKHAC
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$
-- ? giới tính
CREATE PROCEDURE SP_CAPNHAT_GIOITINH(
IN p_MAVIENCHUC CHAR(10),
IN p_GIOITINH VARCHAR(3)
)
BEGIN
UPDATE VIENCHUC
SET GIOITINH = p_GIOITINH
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$
--   ? ngày tuyển
CREATE PROCEDURE SP_CAPNHAT_NGAYTUYENDUNG(
IN p_MAVIENCHUC CHAR(10),
IN p_NGAYTUYENDUNG DATETIME
)
BEGIN
UPDATE VIENCHUC
SET NGAYTUYENDUNG = p_NGAYTUYENDUNG
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$
--   ! số hiệu viên chức
CREATE PROCEDURE SP_CAPNHAT_SOHIEUVIENCHUC(
IN p_MAVIENCHUC CHAR(10),
IN p_SOHIEUVIENCHUC CHAR(10)
)
BEGIN
UPDATE VIENCHUC
SET SOHIEUVIENCHUC = p_SOHIEUVIENCHUC
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$

--  ? ảnh đại diện
CREATE PROCEDURE SP_CAPNHAT_ANHDAIDIEN(
IN p_MAVIENCHUC CHAR(10),
IN p_ANHDAIDIEN TEXT
)
BEGIN
UPDATE VIENCHUC
SET ANHDAIDIEN = p_ANHDAIDIEN
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$


-- ? số bảo hiểm
CREATE PROCEDURE SP_CAPNHAT_SOBAOHIEM(
IN p_MAVIENCHUC CHAR(10),
IN p_SOBAOHIEM CHAR(10)
)
BEGIN
UPDATE VIENCHUC
SET SOBAOHIEM = p_SOBAOHIEM
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$

--   * năm được phong học hàm
CREATE PROCEDURE SP_CAPNHAT_NAMDUOCPHONGHOCHAM(
IN p_MAVIENCHUC CHAR(10),
IN p_NAMDUOCPHONGHOCHAM DATETIME
)
BEGIN
UPDATE VIENCHUC
SET NAMDUOCPHONGHOCHAM = p_NAMDUOCPHONGHOCHAM
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$

--  * năm được phong học vị
CREATE PROCEDURE SP_CAPNHAT_NAMDUOCPHONGDANHHIEU(
IN p_MAVIENCHUC CHAR(10),
IN p_NAMDUOCPHONGDANHHIEU DATETIME
)
BEGIN
UPDATE VIENCHUC
SET NAMDUOCPHONGDANHHIEU = p_NAMDUOCPHONGDANHHIEU
WHERE MAVIENCHUC = p_MAVIENCHUC;
END$$

DELIMITER ;
