-- ! this part is only for admin and thanh tra to view the statistic of employees

--   ? gender
CREATE VIEW VW_THONGKE_GIOITINH AS
SELECT
    GIOITINH,
    COUNT(*) AS SOLUONG
FROM VIENCHUC
GROUP BY GIOITINH;


-- ? enthiicity
CREATE VIEW VW_THONGKE_DANTOC AS
SELECT
    dt.TENDANTOC,
    COUNT(*) AS SOLUONG
FROM VIENCHUC vc
JOIN DANTOC dt ON vc.MADANTOC = dt.MADANTOC
GROUP BY dt.TENDANTOC;

-- ?  religion
CREATE VIEW VW_THONGKE_TONGIAO AS
SELECT
    tg.TENTONGIAO,
    COUNT(*) AS SOLUONG
FROM VIENCHUC vc
LEFT JOIN TONGIAO tg ON vc.MATONGIAO = tg.MATONGIAO
GROUP BY tg.TENTONGIAO;


CREATE VIEW VW_THONGKE_DOTUOI AS
SELECT
    CASE
        WHEN TIMESTAMPDIFF(YEAR, NGAYSINH, CURDATE()) < 30 THEN 'Duoi 30'
        WHEN TIMESTAMPDIFF(YEAR, NGAYSINH, CURDATE()) BETWEEN 30 AND 39 THEN '30-39'
        WHEN TIMESTAMPDIFF(YEAR, NGAYSINH, CURDATE()) BETWEEN 40 AND 49 THEN '40-49'
        WHEN TIMESTAMPDIFF(YEAR, NGAYSINH, CURDATE()) BETWEEN 50 AND 59 THEN '50-59'
        ELSE '60+'
    END AS NHOMTUOI,
    COUNT(*) AS SOLUONG
FROM VIENCHUC
GROUP BY NHOMTUOI;

-- ? education information
CREATE VIEW VW_THONGKE_TRINHDOHOCVAN AS
SELECT
    td.TRINHDONGHIEPVUCHUYENNGANH,
    COUNT(*) AS SOLUONG
FROM VIENCHUC vc
JOIN TRINHDOHOCVAN td
ON vc.MATRINHDO = td.MATRINHDO
GROUP BY td.TRINHDONGHIEPVUCHUYENNGANH;

-- specialized information
CREATE VIEW VW_THONGKE_CHUYENMON AS
SELECT
    cm.TENCHUYENMON,
    COUNT(*) AS SOLUONG
FROM CO_TRDCM_CAONHAT ct
JOIN CHUYENMON cm
ON ct.MACHUYENMON = cm.MACHUYENMON
GROUP BY cm.TENCHUYENMON;

-- ? foreign language information
CREATE VIEW VW_THONGKE_NGOAINGU AS
SELECT
    nn.TENNGOAINGU,
    COUNT(*) AS SOLUONG
FROM CO_TRD_NGOAINGU ct
JOIN NGOAINGU nn
ON ct.MANGOAINGU = nn.MANGOAINGU
GROUP BY nn.TENNGOAINGU;

-- computer skill information
CREATE VIEW VW_THONGKE_TINHOC AS
SELECT
    th.CHUNGCHITINHOC,
    COUNT(*) AS SOLUONG
FROM CO_TRD_TINHOC ct
JOIN CHUNGCHITINHOC th
ON ct.MACHUNGCHITINHOC = th.MACHUNGCHITINHOC
GROUP BY th.CHUNGCHITINHOC;

--    ? count how many employees in each department 
CREATE VIEW VW_THONGKE_COQUAN AS
SELECT
    cq.TENCOQUAN,
    COUNT(DISTINCT ccv.MAVIENCHUC) AS SOLUONG
FROM CO_CHUCVU ccv
JOIN COQUAN cq
ON ccv.MACOQUAN = cq.MACOQUAN
GROUP BY cq.TENCOQUAN;

-- ? count how many employees in each position
CREATE VIEW VW_THONGKE_CHUCVU AS
SELECT
    cv.TENCHUCVU,
    COUNT(*) AS SOLUONG
FROM CO_CHUCVU ccv
JOIN CHUCVU cv
ON ccv.MACHUCVU = cv.MACHUCVU
GROUP BY cv.TENCHUCVU;

-- ? count how many employees in each profession
CREATE VIEW VW_THONGKE_NGHENGHIEP AS
SELECT
    nn.TENNGHENGHIEP,
    COUNT(*) AS SOLUONG
FROM CO_CHUCVU ccv
JOIN CHUCDANH_NGHENGHIEP nn
ON ccv.MANGHENGHIEP = nn.MANGHENGHIEP
GROUP BY nn.TENNGHENGHIEP;

-- ? count how many employees in each reward type
CREATE VIEW VW_THONGKE_KHENTHUONG AS
SELECT
    ht.TENHINHTHUCKHENTHUONG,
    COUNT(*) AS SOLUONG
FROM DUOC_KHENTHUONG dk
JOIN HINHTHUCKHENTHUONG ht
ON dk.MAHINHTHUCKHENTHUONG = ht.MAHINHTHUCKHENTHUONG
GROUP BY ht.TENHINHTHUCKHENTHUONG;

-- thong ke ky luat
CREATE VIEW VW_THONGKE_KYLUAT AS
SELECT
    kl.TENHINHTHUCKYLUAT,
    COUNT(*) AS SOLUONG
FROM BI_KYLUAT bk
JOIN HINHTHUCKYLUAT kl
ON bk.MAHINHTHUCKYLUAT = kl.MAHINHTHUCKYLUAT
GROUP BY kl.TENHINHTHUCKYLUAT;

--   ? count how many employees get reward in EACH YEAR
CREATE VIEW VW_THONGKE_KHENTHUONG_THEONAM AS
SELECT
    YEAR(NAMNHANKHENTHUONG) AS NAM,
    COUNT(*) AS SOLUONG
FROM DUOC_KHENTHUONG
GROUP BY YEAR(NAMNHANKHENTHUONG);


--  ? count how many employees get discipline in EACH YEAR
CREATE VIEW VW_THONGKE_KYLUAT_THEONAM AS
SELECT
    YEAR(NAMBIKYLUAT) AS NAM,
    COUNT(*) AS SOLUONG
FROM BI_KYLUAT
GROUP BY YEAR(NAMBIKYLUAT);

--   ?  count how many employees get recruited in EACH YEAR
CREATE VIEW VW_THONGKE_TUYENDUNG_THEONAM AS
SELECT
    YEAR(NGAYTUYENDUNG) AS NAM,
    COUNT(*) AS SOLUONG
FROM VIENCHUC
GROUP BY YEAR(NGAYTUYENDUNG);


-- ? general overview dashboard
CREATE VIEW VW_DASHBOARD_TONGQUAN AS
SELECT
    (SELECT COUNT(*) FROM VIENCHUC) AS TONGVIENCHUC,

    (SELECT COUNT(*)
     FROM VIENCHUC
     WHERE GIOITINH = 'Nam') AS NAM,

    (SELECT COUNT(*)
     FROM VIENCHUC
     WHERE GIOITINH = 'Nu') AS NU,

    (SELECT COUNT(DISTINCT MAVIENCHUC)
     FROM DUOC_KHENTHUONG) AS SO_NGUOI_DUOC_KHENTHUONG,

    (SELECT COUNT(DISTINCT MAVIENCHUC)
     FROM BI_KYLUAT) AS SO_NGUOI_BI_KYLUAT;

-- ? health (honestly... i don't know if i need thhis, cause if my old job said anything it's just no one care about employee healtht)
CREATE VIEW VW_THONGKE_TINHTRANGSUCKHOE AS
SELECT
    sk.TINHTRANGSUCKHOE,
    COUNT(*) AS SOLUONG
FROM CO_TINHTRANGSK ct
JOIN TINHTRANGSUCKHOE sk
ON ct.MASUCKHOE = sk.MASUCKHOE
GROUP BY sk.TINHTRANGSUCKHOE;

