DELIMITER $$

CREATE PROCEDURE SP_THEM_USERS (
    IN p_mavienchuc CHAR(10),
    IN p_role VARCHAR(20)
)
BEGIN
    DECLARE db_role VARCHAR(30);

    IF p_role = 'admin' THEN
        SET db_role = 'admin_role';
    ELSEIF p_role = 'hr' THEN
        SET db_role = 'hr_role';
    ELSEIF p_role = 'vienchuc' THEN
        SET db_role = 'vienchuc_role';
    ELSE
        SET db_role = 'thanhtra_role';
    END IF;

    INSERT INTO USERS (MAVIENCHUC, PASSWORD, ROLE)
    VALUES (p_mavienchuc, p_mavienchuc, p_role);

    -- create user
    SET @sql = CONCAT("CREATE USER '", p_mavienchuc, "'@'%' IDENTIFIED BY '", p_mavienchuc, "'");
    PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

    -- ass role
    SET @sql2 = CONCAT("GRANT '", db_role, "' TO '", p_mavienchuc, "'@'%'");
    PREPARE stmt2 FROM @sql2; EXECUTE stmt2; DEALLOCATE PREPARE stmt2;
    
    -- default
    SET @sql3 = CONCAT("SET DEFAULT ROLE '", db_role, "' TO '", p_mavienchuc, "'@'%'");
    PREPARE stmt3 FROM @sql3; EXECUTE stmt3; DEALLOCATE PREPARE stmt3;
END$$

DELIMITER ;


DELIMITER $$
CREATE PROCEDURE SP_THEM_VIENCHUC (
    IN p_MAVIENCHUC CHAR(10), IN p_MADANHHIEU CHAR(5), IN p_MATONGIAO CHAR(5),
    IN p_MAHOCHAM CHAR(5), IN p_MATRINHDO CHAR(5), IN p_MADANTOC CHAR(5),
    IN p_MAHANGTHUONGBINH CHAR(5), IN p_MAXAPHUONG CHAR(5), IN p_XAP_MAXAPHUONG CHAR(5),
    IN p_HO VARCHAR(20), IN p_TENLOT VARCHAR(40), IN p_TEN VARCHAR(20), IN p_TENKHAC VARCHAR(100),
    IN p_NGAYSINH DATETIME, IN p_GIOITINH VARCHAR(3), IN p_NGAYTUYENDUNG DATETIME,
    IN p_SOHIEUVIENCHUC CHAR(10), IN p_ANHDAIDIEN TEXT, IN p_SOCCCD CHAR(12),
    IN p_NOICAPCCCD CHAR(100), IN p_NGAYCAPCCCD DATETIME, IN p_SOBAOHIEM CHAR(10),
    IN p_NHOMMAU CHAR(3), IN p_NAMDUOCPHONGHOCHAM DATETIME, IN p_NAMDUOCPHONGDANHHIEU DATETIME,
    IN p_role VARCHAR(20)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    START TRANSACTION;

    INSERT INTO VIENCHUC (
        MAVIENCHUC, MADANHHIEU, MATONGIAO, MAHOCHAM, MATRINHDO, MADANTOC, 
        MAHANGTHUONGBINH, MAXAPHUONG, XAP_MAXAPHUONG, HO, TENLOT, TEN, 
        TENKHAC, NGAYSINH, GIOITINH, NGAYTUYENDUNG, SOHIEUVIENCHUC, 
        ANHDAIDIEN, SOCCCD, NOICAPCCCD, NGAYCAPCCCD, SOBAOHIEM, NHOMMAU, 
        NAMDUOCPHONGHOCHAM, NAMDUOCPHONGDANHHIEU
    ) 
    VALUES (
        p_MAVIENCHUC, p_MADANHHIEU, p_MATONGIAO, p_MAHOCHAM, p_MATRINHDO, p_MADANTOC, 
        p_MAHANGTHUONGBINH, p_MAXAPHUONG, p_XAP_MAXAPHUONG, p_HO, p_TENLOT, p_TEN, 
        p_TENKHAC, p_NGAYSINH, p_GIOITINH, p_NGAYTUYENDUNG, p_SOHIEUVIENCHUC, 
        p_ANHDAIDIEN, p_SOCCCD, p_NOICAPCCCD, p_NGAYCAPCCCD, p_SOBAOHIEM, p_NHOMMAU, 
        p_NAMDUOCPHONGHOCHAM, p_NAMDUOCPHONGDANHHIEU
    );

    CALL SP_THEM_USERS(p_MAVIENCHUC, p_role);

    COMMIT;
END$$

DELIMITER ;


DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_USERS (
    IN p_mavienchuc CHAR(10),
    IN p_role VARCHAR(20)
)
BEGIN
    DECLARE old_role VARCHAR(20);
    DECLARE old_db_role VARCHAR(30);
    DECLARE new_db_role VARCHAR(30);

    SELECT ROLE INTO old_role FROM USERS WHERE MAVIENCHUC = p_mavienchuc;

    --  ? old role
    IF old_role = 'admin' THEN SET old_db_role = 'admin_role';
    ELSEIF old_role = 'hr' THEN SET old_db_role = 'hr_role';
    ELSEIF old_role = 'vienchuc' THEN SET old_db_role = 'vienchuc_role';
    ELSE SET old_db_role = 'thanhtra_role';
    END IF;

    -- ? new role
    IF p_role = 'admin' THEN SET new_db_role = 'admin_role';
    ELSEIF p_role = 'hr' THEN SET new_db_role = 'hr_role';
    ELSEIF p_role = 'vienchuc' THEN SET new_db_role = 'vienchuc_role';
    ELSE SET new_db_role = 'thanhtra_role';
    END IF;

    -- ? update system
    UPDATE USERS SET ROLE = p_role WHERE MAVIENCHUC = p_mavienchuc;


    IF old_db_role <> new_db_role THEN
        SET @sql_revoke = CONCAT("REVOKE '", old_db_role, "' FROM '", p_mavienchuc, "'@'%'");
        PREPARE stmt_rev FROM @sql_revoke; EXECUTE stmt_rev; DEALLOCATE PREPARE stmt_rev;

        SET @sql_grant = CONCAT("GRANT '", new_db_role, "' TO '", p_mavienchuc, "'@'%'");
        PREPARE stmt_gnt FROM @sql_grant; EXECUTE stmt_gnt; DEALLOCATE PREPARE stmt_gnt;

        SET @sql_def = CONCAT("SET DEFAULT ROLE '", new_db_role, "' TO '", p_mavienchuc, "'@'%'");
        PREPARE stmt_def FROM @sql_def; EXECUTE stmt_def; DEALLOCATE PREPARE stmt_def;
    END IF;
END$$
DELIMITER ;



DELIMITER $$

CREATE PROCEDURE SP_XOA_USERS (
    IN p_mavienchuc CHAR(10)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        RESIGNAL;
    END;

    SET @sql = CONCAT(
        "DROP USER IF EXISTS '",
        p_mavienchuc,
        "'@'%'"
    );

    PREPARE stmt FROM @sql;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;

    DELETE FROM USERS
    WHERE MAVIENCHUC = p_mavienchuc;

END$$

DELIMITER ;

--    *      VIÊN CHỨC 
DELIMITER $$
CREATE PROCEDURE SP_CAPNHAT_VIENCHUC (
    IN p_MAVIENCHUC CHAR(10), IN p_MADANHHIEU CHAR(5), IN p_MATONGIAO CHAR(5),
    IN p_MAHOCHAM CHAR(5), IN p_MATRINHDO CHAR(5), IN p_MADANTOC CHAR(5),
    IN p_MAHANGTHUONGBINH CHAR(5), IN p_MAXAPHUONG CHAR(5), IN p_XAP_MAXAPHUONG CHAR(5),
    IN p_HO VARCHAR(20), IN p_TENLOT VARCHAR(40), IN p_TEN VARCHAR(20), IN p_TENKHAC VARCHAR(100),
    IN p_NGAYSINH DATETIME, IN p_GIOITINH VARCHAR(3), IN p_NGAYTUYENDUNG DATETIME,
    IN p_SOHIEUVIENCHUC CHAR(10), IN p_ANHDAIDIEN TEXT, IN p_SOCCCD CHAR(10),
    IN p_NOICAPCCCD CHAR(100), IN p_NGAYCAPCCCD DATETIME, IN p_SOBAOHIEM CHAR(10),
    IN p_NHOMMAU CHAR(3), IN p_NAMDUOCPHONGHOCHAM DATETIME, IN p_NAMDUOCPHONGDANHHIEU DATETIME,
    IN p_role VARCHAR(20)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    START TRANSACTION;

    UPDATE VIENCHUC SET
        MADANHHIEU = p_MADANHHIEU, MATONGIAO = p_MATONGIAO, MAHOCHAM = p_MAHOCHAM,
        MATRINHDO = p_MATRINHDO, MADANTOC = p_MADANTOC, MAHANGTHUONGBINH = p_MAHANGTHUONGBINH,
        MAXAPHUONG = p_MAXAPHUONG, XAP_MAXAPHUONG = p_XAP_MAXAPHUONG, HO = p_HO,
        TENLOT = p_TENLOT, TEN = p_TEN, TENKHAC = p_TENKHAC, NGAYSINH = p_NGAYSINH,
        GIOITINH = p_GIOITINH, NGAYTUYENDUNG = p_NGAYTUYENDUNG, SOHIEUVIENCHUC = p_SOHIEUVIENCHUC,
        ANHDAIDIEN = p_ANHDAIDIEN, SOCCCD = p_SOCCCD, NOICAPCCCD = p_NOICAPCCCD,
        NGAYCAPCCCD = p_NGAYCAPCCCD, SOBAOHIEM = p_SOBAOHIEM, NHOMMAU = p_NHOMMAU,
        NAMDUOCPHONGHOCHAM = p_NAMDUOCPHONGHOCHAM, NAMDUOCPHONGDANHHIEU = p_NAMDUOCPHONGDANHHIEU
    WHERE MAVIENCHUC = p_MAVIENCHUC;

    CALL SP_CAPNHAT_USERS(p_MAVIENCHUC, p_role);

    COMMIT;
END$$

DELIMITER ;


DELIMITER $$

CREATE PROCEDURE SP_XOA_VIENCHUC (
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    START TRANSACTION;
    DELETE FROM DUOC_KHENTHUONG WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM BI_KYLUAT WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM CO_CAPLYLUANCHINHTRI WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM CO_CAPQUANLYNHANUOC WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM CO_CHUCVU WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM CO_HOKHAUTHUONGTRU WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM CO_TAMTRU WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM CO_TINHTRANGSK WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM CO_TRDCM_CAONHAT WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM CO_TRD_NGOAINGU WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM CO_TRD_TINHOC WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM THUOC_QUANDOI WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM THUOC_TOCHUCDOANTHECHINHTRIXAHOI WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM TUYENDUNG WHERE MAVIENCHUC = p_MAVIENCHUC;
    DELETE FROM THUOC_NHOM_NGACH WHERE MAVIENCHUC = p_MAVIENCHUC;

    CALL SP_XOA_USERS(p_MAVIENCHUC);

    DELETE FROM VIENCHUC WHERE MAVIENCHUC = p_MAVIENCHUC;

    COMMIT;
END$$

DELIMITER ;

--  ?  KHEN THUONG
DELIMITER $$



CREATE PROCEDURE SP_CAPNHAT_DUOC_KHENTHUONG (
    IN p_MAHINHTHUCKHENTHUONG CHAR(5),
    IN p_MAVIENCHUC CHAR(10),
    IN p_NAMNHANKHENTHUONG DATETIME,
    IN p_SOQUYETDINHKHENTHUONG CHAR(50),
    IN p_NGUOIKYQUYETDINHKHENTHUONG CHAR(150)
)
BEGIN
    INSERT INTO DUOC_KHENTHUONG (
        MAHINHTHUCKHENTHUONG, MAVIENCHUC, NAMNHANKHENTHUONG, 
        SOQUYETDINHKHENTHUONG, NGUOIKYQUYETDINHKHENTHUONG
    )
    VALUES (
        p_MAHINHTHUCKHENTHUONG, p_MAVIENCHUC, p_NAMNHANKHENTHUONG, 
        p_SOQUYETDINHKHENTHUONG, p_NGUOIKYQUYETDINHKHENTHUONG
    )
    ON DUPLICATE KEY UPDATE
        NAMNHANKHENTHUONG = p_NAMNHANKHENTHUONG,
        SOQUYETDINHKHENTHUONG = p_SOQUYETDINHKHENTHUONG,
        NGUOIKYQUYETDINHKHENTHUONG = p_NGUOIKYQUYETDINHKHENTHUONG;
END$$

DELIMITER ;


DELIMITER $$
CREATE PROCEDURE SP_XOA_DUOC_KHENTHUONG (
    IN p_MAHINHTHUCKHENTHUONG CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    DELETE FROM DUOC_KHENTHUONG
    WHERE MAHINHTHUCKHENTHUONG = p_MAHINHTHUCKHENTHUONG AND MAVIENCHUC = p_MAVIENCHUC;
END$$
DELiMITER ;



--       ?         Kỷluật
DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_BI_KYLUAT (
    IN p_MAHINHTHUCKYLUAT CHAR(5),
    IN p_MAVIENCHUC CHAR(10),
    IN p_NAMBIKYLUAT DATETIME,
    IN p_SOQUYETDINHKYLUAT CHAR(50),
    IN p_NGUOIKYQUYETDINHKYLUAT CHAR(150)
)
BEGIN
    INSERT INTO BI_KYLUAT (
        MAHINHTHUCKYLUAT, MAVIENCHUC, NAMBIKYLUAT, 
        SOQUYETDINHKYLUAT, NGUOIKYQUYETDINHKYLUAT
    )
    VALUES (
        p_MAHINHTHUCKYLUAT, p_MAVIENCHUC, p_NAMBIKYLUAT, 
        p_SOQUYETDINHKYLUAT, p_NGUOIKYQUYETDINHKYLUAT
    )
    ON DUPLICATE KEY UPDATE
        NAMBIKYLUAT = p_NAMBIKYLUAT,
        SOQUYETDINHKYLUAT = p_SOQUYETDINHKYLUAT,
        NGUOIKYQUYETDINHKYLUAT = p_NGUOIKYQUYETDINHKYLUAT;
END$$

DELIMITER ;

DELIMITER $$

CREATE PROCEDURE SP_XOA_BI_KYLUAT (
    IN p_MAHINHTHUCKYLUAT CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    DELETE FROM BI_KYLUAT
    WHERE MAHINHTHUCKYLUAT = p_MAHINHTHUCKYLUAT AND MAVIENCHUC = p_MAVIENCHUC;
END$$
DELiMITER ;

-- ?  COS Cấp luận chính trị

DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_CO_CAPLYLUANCHINHTRI (
    IN p_MACAPCT CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    INSERT INTO CO_CAPLYLUANCHINHTRI (MACAPCT, MAVIENCHUC)
    VALUES (p_MACAPCT, p_MAVIENCHUC)
    ON DUPLICATE KEY UPDATE MACAPCT = p_MACAPCT;
END$$

CREATE PROCEDURE SP_XOA_CO_CAPLYLUANCHINHTRI (
    IN p_MACAPCT CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    DELETE FROM CO_CAPLYLUANCHINHTRI 
    WHERE MACAPCT = p_MACAPCT AND MAVIENCHUC = p_MAVIENCHUC;
END$$

DELIMITER ;

--   ?   COS Cấp quản lý nhà nước
DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_CO_CAPQUANLYNHANUOC (
    IN p_MACAPQLNN CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    INSERT INTO CO_CAPQUANLYNHANUOC (MACAPQLNN, MAVIENCHUC)
    VALUES (p_MACAPQLNN, p_MAVIENCHUC)
    ON DUPLICATE KEY UPDATE MACAPQLNN = p_MACAPQLNN;
END$$
-- ! DEL
CREATE PROCEDURE SP_XOA_CO_CAPQUANLYNHANUOC (
    IN p_MACAPQLNN CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    DELETE FROM CO_CAPQUANLYNHANUOC 
    WHERE MACAPQLNN = p_MACAPQLNN AND MAVIENCHUC = p_MAVIENCHUC;
END$$

DELIMITER ;

--   ?   Có Chức vụ
DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_CO_CHUCVU (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MACHUCVU CHAR(5),
    IN p_MACOQUAN CHAR(5),
    IN p_MANGHENGHIEP CHAR(5),
    IN p_THOIGIANGIUCHUCVU DATETIME,
    IN p_THOIGIANKETTHUCCHUCVU DATETIME
)
BEGIN
    INSERT INTO CO_CHUCVU (MAVIENCHUC, MACHUCVU, MACOQUAN, MANGHENGHIEP, THOIGIANGIUCHUCVU, THOIGIANKETTHUCCHUCVU)
    VALUES (p_MAVIENCHUC, p_MACHUCVU, p_MACOQUAN, p_MANGHENGHIEP, p_THOIGIANGIUCHUCVU, p_THOIGIANKETTHUCCHUCVU)
    ON DUPLICATE KEY UPDATE 
        THOIGIANGIUCHUCVU = p_THOIGIANGIUCHUCVU,
        THOIGIANKETTHUCCHUCVU = p_THOIGIANKETTHUCCHUCVU;
END$$
-- ! DEL
CREATE PROCEDURE SP_XOA_CO_CHUCVU (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MACHUCVU CHAR(5),
    IN p_MACOQUAN CHAR(5),
    IN p_MANGHENGHIEP CHAR(5)
)
BEGIN
    DELETE FROM CO_CHUCVU 
    WHERE MAVIENCHUC = p_MAVIENCHUC 
      AND MACHUCVU = p_MACHUCVU 
      AND MACOQUAN = p_MACOQUAN 
      AND MANGHENGHIEP = p_MANGHENGHIEP;
END$$

DELIMITER ;


-- ? co hệ số lương
DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_CO_HESOLUONG (
    IN p_MABACLUONG CHAR(5),
    IN p_MANHOMNGACH CHAR(4),
    IN p_MACHITIETLUONG CHAR(5),
    IN p_HESOLUONG DECIMAL(5,3)
)
BEGIN
    INSERT INTO CO_HESOLUONG (MABACLUONG, MANHOMNGACH, MACHITIETLUONG, HESOLUONG)
    VALUES (p_MABACLUONG, p_MANHOMNGACH, p_MACHITIETLUONG, p_HESOLUONG)
    ON DUPLICATE KEY UPDATE HESOLUONG = p_HESOLUONG;
END$$
-- ! DEL
CREATE PROCEDURE SP_XOA_CO_HESOLUONG (
    IN p_MABACLUONG CHAR(5),
    IN p_MANHOMNGACH CHAR(4),
    IN p_MACHITIETLUONG CHAR(5)
)
BEGIN
    DELETE FROM CO_HESOLUONG 
    WHERE MABACLUONG = p_MABACLUONG 
      AND MANHOMNGACH = p_MANHOMNGACH 
      AND MACHITIETLUONG = p_MACHITIETLUONG;
END$$

DELIMITER ;


--   ?    CÓ Hộ khẩu thường trú
DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_CO_HOKHAUTHUONGTRU (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MAXAPHUONG CHAR(5),
    IN p_THOIGIANDANGKYHOKHAU DATETIME
)
BEGIN
    INSERT INTO CO_HOKHAUTHUONGTRU (MAVIENCHUC, MAXAPHUONG, THOIGIANDANGKYHOKHAU)
    VALUES (p_MAVIENCHUC, p_MAXAPHUONG, p_THOIGIANDANGKYHOKHAU)
    ON DUPLICATE KEY UPDATE THOIGIANDANGKYHOKHAU = p_THOIGIANDANGKYHOKHAU;
END$$
-- ! DEL

CREATE PROCEDURE SP_XOA_CO_HOKHAUTHUONGTRU (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MAXAPHUONG CHAR(5)
)
BEGIN
    DELETE FROM CO_HOKHAUTHUONGTRU 
    WHERE MAVIENCHUC = p_MAVIENCHUC AND MAXAPHUONG = p_MAXAPHUONG;
END$$

DELIMITER ;

--  ! cótạm trú

DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_CO_TAMTRU (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MAXAPHUONG CHAR(5),
    IN p_THOIGIANDANGKYTAMTRU DATETIME
)
BEGIN
    INSERT INTO CO_TAMTRU (MAVIENCHUC, MAXAPHUONG, THOIGIANDANGKYTAMTRU)
    VALUES (p_MAVIENCHUC, p_MAXAPHUONG, p_THOIGIANDANGKYTAMTRU)
    ON DUPLICATE KEY UPDATE THOIGIANDANGKYTAMTRU = p_THOIGIANDANGKYTAMTRU;
END$$

CREATE PROCEDURE SP_XOA_CO_TAMTRU (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MAXAPHUONG CHAR(5)
)
BEGIN
    DELETE FROM CO_TAMTRU 
    WHERE MAVIENCHUC = p_MAVIENCHUC AND MAXAPHUONG = p_MAXAPHUONG;
END$$

DELIMITER ;

--  ? CÓ Tình trạng sức khỏe

DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_CO_TINHTRANGSK (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MASUCKHOE CHAR(5),
    IN p_CANNANG DECIMAL(4,2),
    IN p_CHIEUCAO TINYINT,
    IN p_THOIGIANGHINHAN DATETIME
)
BEGIN
    INSERT INTO CO_TINHTRANGSK (MAVIENCHUC, MASUCKHOE, CANNANG, CHIEUCAO, THOIGIANGHINHAN)
    VALUES (p_MAVIENCHUC, p_MASUCKHOE, p_CANNANG, p_CHIEUCAO, p_THOIGIANGHINHAN)
    ON DUPLICATE KEY UPDATE 
        CANNANG = p_CANNANG,
        CHIEUCAO = p_CHIEUCAO,
        THOIGIANGHINHAN = p_THOIGIANGHINHAN;
END$$

CREATE PROCEDURE SP_XOA_CO_TINHTRANGSK (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MASUCKHOE CHAR(5)
)
BEGIN
    DELETE FROM CO_TINHTRANGSK 
    WHERE MAVIENCHUC = p_MAVIENCHUC AND MASUCKHOE = p_MASUCKHOE;
END$$

DELIMITER ;

--  ? Trình độc chuyên môn cao nhất
DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_CO_TRDCM_CAONHAT (
    IN p_MACHUYENMON CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    INSERT INTO CO_TRDCM_CAONHAT (MACHUYENMON, MAVIENCHUC)
    VALUES (p_MACHUYENMON, p_MAVIENCHUC)
    ON DUPLICATE KEY UPDATE MACHUYENMON = p_MACHUYENMON;
END$$

CREATE PROCEDURE SP_XOA_CO_TRDCM_CAONHAT (
    IN p_MACHUYENMON CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    DELETE FROM CO_TRDCM_CAONHAT 
    WHERE MACHUYENMON = p_MACHUYENMON AND MAVIENCHUC = p_MAVIENCHUC;
END$$

DELIMITER ;


-- ? Có trình độ ngoại ngữ
DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_CO_TRD_NGOAINGU (
    IN p_MANGOAINGU CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    INSERT INTO CO_TRD_NGOAINGU (MANGOAINGU, MAVIENCHUC)
    VALUES (p_MANGOAINGU, p_MAVIENCHUC)
    ON DUPLICATE KEY UPDATE MANGOAINGU = p_MANGOAINGU;
END$$

CREATE PROCEDURE SP_XOA_CO_TRD_NGOAINGU (
    IN p_MANGOAINGU CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    DELETE FROM CO_TRD_NGOAINGU 
    WHERE MANGOAINGU = p_MANGOAINGU AND MAVIENCHUC = p_MAVIENCHUC;
END$$

DELIMITER ;

-- ? CÓ trình độ tin học
DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_CO_TRD_TINHOC (
    IN p_MACHUNGCHITINHOC CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    INSERT INTO CO_TRD_TINHOC (MACHUNGCHITINHOC, MAVIENCHUC)
    VALUES (p_MACHUNGCHITINHOC, p_MAVIENCHUC)
    ON DUPLICATE KEY UPDATE MACHUNGCHITINHOC = p_MACHUNGCHITINHOC;
END$$

CREATE PROCEDURE SP_XOA_CO_TRD_TINHOC (
    IN p_MACHUNGCHITINHOC CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    DELETE FROM CO_TRD_TINHOC 
    WHERE MACHUNGCHITINHOC = p_MACHUNGCHITINHOC AND MAVIENCHUC = p_MAVIENCHUC;
END$$

DELIMITER ;

-- ? thuộc quân đôi

DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_THUOC_QUANDOI (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MATTD_QD CHAR(5),
    IN p_MAQUANHAM CHAR(5),
    IN p_NGAYNHAPNGU DATETIME,
    IN p_NGAYXUATNGU DATETIME,
    IN p_NOINHAPNGU TEXT
)
BEGIN
    INSERT INTO THUOC_QUANDOI (MAVIENCHUC, MATTD_QD, MAQUANHAM, NGAYNHAPNGU, NGAYXUATNGU, NOINHAPNGU)
    VALUES (p_MAVIENCHUC, p_MATTD_QD, p_MAQUANHAM, p_NGAYNHAPNGU, p_NGAYXUATNGU, p_NOINHAPNGU)
    ON DUPLICATE KEY UPDATE 
        NGAYNHAPNGU = p_NGAYNHAPNGU,
        NGAYXUATNGU = p_NGAYXUATNGU,
        NOINHAPNGU = p_NOINHAPNGU;
END$$

CREATE PROCEDURE SP_XOA_THUOC_QUANDOI (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MATTD_QD CHAR(5),
    IN p_MAQUANHAM CHAR(5)
)
BEGIN
    DELETE FROM THUOC_QUANDOI 
    WHERE MAVIENCHUC = p_MAVIENCHUC AND MATTD_QD = p_MATTD_QD AND MAQUANHAM = p_MAQUANHAM;
END$$

DELIMITER ;

-- ? THUỘC TỔ CHỨC ĐOÀN THỂ CHÍNH TRỊ XÃ HỘI
-- ! HOLY SHIT THE NAME IS SO STUPIDLY LONG
DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_THUOC_TCDT_CTXH (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MATOCHUCDTCTXH CHAR(5),
    IN p_NGAYVAOTOCHUC DATETIME,
    IN p_NGAYCHINHTHUC DATETIME,
    IN p_NGUOIGIOITHIEU TEXT,
    IN p_LANVAOTOCHUC TINYINT
)
BEGIN
    INSERT INTO THUOC_TOCHUCDOANTHECHINHTRIXAHOI (
        MAVIENCHUC, MATOCHUCDTCTXH, NGAYVAOTOCHUC, NGAYCHINHTHUC, NGUOIGIOITHIEU, LANVAOTOCHUC
    )
    VALUES (
        p_MAVIENCHUC, p_MATOCHUCDTCTXH, p_NGAYVAOTOCHUC, p_NGAYCHINHTHUC, p_NGUOIGIOITHIEU, p_LANVAOTOCHUC
    )
    ON DUPLICATE KEY UPDATE 
        NGAYVAOTOCHUC = p_NGAYVAOTOCHUC,
        NGAYCHINHTHUC = p_NGAYCHINHTHUC,
        NGUOIGIOITHIEU = p_NGUOIGIOITHIEU,
        LANVAOTOCHUC = p_LANVAOTOCHUC;
END$$

CREATE PROCEDURE SP_XOA_THUOC_TCDT_CTXH (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MATOCHUCDTCTXH CHAR(5)
)
BEGIN
    DELETE FROM THUOC_TOCHUCDOANTHECHINHTRIXAHOI 
    WHERE MAVIENCHUC = p_MAVIENCHUC AND MATOCHUCDTCTXH = p_MATOCHUCDTCTXH;
END$$

DELIMITER ;

-- ? TUYỂN DỤNG
DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_TUYENDUNG (
    IN p_MANGHENGHIEP CHAR(5),
    IN p_MAVIENCHUC CHAR(10),
    IN p_MACOQUAN CHAR(5),
    IN p_NGAYTUYENDUNG DATETIME
)
BEGIN
    INSERT INTO TUYENDUNG (MANGHENGHIEP, MAVIENCHUC, MACOQUAN, NGAYTUYENDUNG)
    VALUES (p_MANGHENGHIEP, p_MAVIENCHUC, p_MACOQUAN, p_NGAYTUYENDUNG)
    ON DUPLICATE KEY UPDATE NGAYTUYENDUNG = p_NGAYTUYENDUNG;
END$$

CREATE PROCEDURE SP_XOA_TUYENDUNG (
    IN p_MANGHENGHIEP CHAR(5),
    IN p_MAVIENCHUC CHAR(10),
    IN p_MACOQUAN CHAR(5)
)
BEGIN
    DELETE FROM TUYENDUNG 
    WHERE MANGHENGHIEP = p_MANGHENGHIEP AND MAVIENCHUC = p_MAVIENCHUC AND MACOQUAN = p_MACOQUAN;
END$$

DELIMITER ;

-- ? Xa Phường

DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_XAPHUONG (
    IN p_MAXAPHUONG CHAR(5),
    IN p_MATINHTHANH CHAR(5),
    IN p_TENXAPHUONG VARCHAR(30)
)
BEGIN
    INSERT INTO XAPHUONG (MAXAPHUONG, MATINHTHANH, TENXAPHUONG)
    VALUES (p_MAXAPHUONG, p_MATINHTHANH, p_TENXAPHUONG)
    ON DUPLICATE KEY UPDATE 
        MATINHTHANH = p_MATINHTHANH,
        TENXAPHUONG = p_TENXAPHUONG;
END$$

CREATE PROCEDURE SP_XOA_XAPHUONG (
    IN p_MAXAPHUONG CHAR(5)
)
BEGIN
    DELETE FROM XAPHUONG WHERE MAXAPHUONG = p_MAXAPHUONG;
END$$

DELIMITER ;


-- ? NHÓM NGẠCH
DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_THUOC_NHOMNGACH (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MACHITIETLUONG CHAR(5),
    IN p_THOIGIANBATDAUHUONG DATETIME

)
BEGIN
    INSERT INTO THUOC_NHOM_NGACH (MAVIENCHUC, MACHITIETLUONG, THOIGIANBATDAUHUONG)
    VALUES (p_MAVIENCHUC, p_MACHITIETLUONG, p_THOIGIANBATDAUHUONG)
    ON DUPLICATE KEY UPDATE
        MACHITIETLUONG = p_MACHITIETLUONG,
        THOIGIANBATDAUHUONG = p_THOIGIANBATDAUHUONG;
END$$

CREATE PROCEDURE SP_XOA_NHOMNGACH (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MACHITIETLUONG CHAR(5)
)
BEGIN
    DELETE FROM THUOC_NHOM_NGACH 
    WHERE MAVIENCHUC = p_MAVIENCHUC AND MACHITIETLUONG = p_MACHITIETLUONG;
END$$

DELIMITER ;

--             !               SIEU QUAN TRONG THONG KE SIEU DANH SACH


DELIMITER //

CREATE PROCEDURE SP_DASHBOARD_CHITIET_NHANSU(
    IN p_TinhTrangSucKhoe VARCHAR(20),  -- Matches TINHTRANGSUCKHOE.TINHTRANGSUCKHOE
    IN p_NhomTuoi VARCHAR(20),          -- 'Duoi 30', '30-39', '40-49', '50-59', '60+'
    IN p_TenCoQuan VARCHAR(30),         -- Matches COQUAN.TENCOQUAN
    IN p_TenChucVu CHAR(30),           -- Matches CHUCVU.TENCHUCVU
    IN p_GioiTinh VARCHAR(3),           -- Matches VIENCHUC.GIOITINH ('Nam' / 'Nu')
    IN p_NamKhenThuong INT,             -- Year of reward
    IN p_NamKyLuat INT                  -- Year of discipline
)
BEGIN
    SELECT DISTINCT
        vc.MAVIENCHUC,
        CONCAT(vc.HO, ' ', vc.TENLOT, ' ', vc.TEN) AS HOTEN,
        vc.GIOITINH,
        vc.NGAYSINH,
        TIMESTAMPDIFF(YEAR, vc.NGAYSINH, CURDATE()) AS TUOI,
        sk.TINHTRANGSUCKHOE,
        cq.TENCOQUAN,
        cv.TENCHUCVU
    FROM VIENCHUC vc

    LEFT JOIN CO_TINHTRANGSK ctsk ON vc.MAVIENCHUC = ctsk.MAVIENCHUC
    LEFT JOIN TINHTRANGSUCKHOE sk ON ctsk.MASUCKHOE = sk.MASUCKHOE
    
    LEFT JOIN CO_CHUCVU ccv ON vc.MAVIENCHUC = ccv.MAVIENCHUC
    LEFT JOIN COQUAN cq ON ccv.MACOQUAN = cq.MACOQUAN
    LEFT JOIN CHUCVU cv ON ccv.MACHUCVU = cv.MACHUCVU
    
    LEFT JOIN DUOC_KHENTHUONG dk ON vc.MAVIENCHUC = dk.MAVIENCHUC
    LEFT JOIN BI_KYLUAT bk ON vc.MAVIENCHUC = bk.MAVIENCHUC
    
    WHERE 
        (p_TinhTrangSucKhoe IS NULL OR sk.TINHTRANGSUCKHOE = p_TinhTrangSucKhoe)
        
        AND (p_GioiTinh IS NULL OR vc.GIOITINH = p_GioiTinh)
        
        AND (p_TenCoQuan IS NULL OR cq.TENCOQUAN = p_TenCoQuan)
        
        AND (p_TenChucVu IS NULL OR cv.TENCHUCVU = p_TenChucVu)
        
        AND (p_NamKhenThuong IS NULL OR YEAR(dk.NAMNHANKHENTHUONG) = p_NamKhenThuong)
        
        AND (p_NamKyLuat IS NULL OR YEAR(bk.NAMBIKYLUAT) = p_NamKyLuat)
        
        AND (
            p_NhomTuoi IS NULL OR
            (p_NhomTuoi = 'Duoi 30' AND TIMESTAMPDIFF(YEAR, vc.NGAYSINH, CURDATE()) < 30) OR
            (p_NhomTuoi = '30-39' AND TIMESTAMPDIFF(YEAR, vc.NGAYSINH, CURDATE()) BETWEEN 30 AND 39) OR
            (p_NhomTuoi = '40-49' AND TIMESTAMPDIFF(YEAR, vc.NGAYSINH, CURDATE()) BETWEEN 40 AND 49) OR
            (p_NhomTuoi = '50-59' AND TIMESTAMPDIFF(YEAR, vc.NGAYSINH, CURDATE()) BETWEEN 50 AND 59) OR
            (p_NhomTuoi = '60+' AND TIMESTAMPDIFF(YEAR, vc.NGAYSINH, CURDATE()) >= 60)
        );
END //

DELIMITER ;

DELIMITER $$

CREATE PROCEDURE SP_LAY_DANH_SACH_THEO_CHI_SO(
    IN p_Category VARCHAR(50),
    IN p_Value VARCHAR(100)
)
BEGIN
    SET @sql = 'SELECT vc.MAVIENCHUC, 
                       CONCAT(vc.HO, '' '', vc.TENLOT, '' '', vc.TEN) AS HOTEN, 
                       vc.GIOITINH, 
                       vc.NGAYSINH,
                       cq.TENCOQUAN,
                       cv.TENCHUCVU ';

    -- All conditions must be inside one IF...ELSEIF...ELSE chain
    IF p_Category = 'suckhoe' THEN
        SET @sql = CONCAT(@sql, ', sk.TINHTRANGSUCKHOE AS TIEUCHI 
                    FROM VIENCHUC vc
                    JOIN CO_TINHTRANGSK ctsk ON vc.MAVIENCHUC = ctsk.MAVIENCHUC
                    JOIN TINHTRANGSUCKHOE sk ON ctsk.MASUCKHOE = sk.MASUCKHOE
                    LEFT JOIN CO_CHUCVU ccv ON vc.MAVIENCHUC = ccv.MAVIENCHUC
                    LEFT JOIN COQUAN cq ON ccv.MACOQUAN = cq.MACOQUAN
                    LEFT JOIN CHUCVU cv ON ccv.MACHUCVU = cv.MACHUCVU
                    WHERE 1=1 ');
        IF p_Value IS NOT NULL AND p_Value <> '' THEN
            SET @sql = CONCAT(@sql, ' AND sk.TINHTRANGSUCKHOE LIKE ''%', p_Value, '%'' ');
        END IF;

    ELSEIF p_Category = 'dotuoi' THEN
        SET @sql = CONCAT(@sql, ', CASE
                        WHEN TIMESTAMPDIFF(YEAR, vc.NGAYSINH, CURDATE()) < 30 THEN ''Duoi 30''
                        WHEN TIMESTAMPDIFF(YEAR, vc.NGAYSINH, CURDATE()) BETWEEN 30 AND 39 THEN ''30-39''
                        WHEN TIMESTAMPDIFF(YEAR, vc.NGAYSINH, CURDATE()) BETWEEN 40 AND 49 THEN ''40-49''
                        WHEN TIMESTAMPDIFF(YEAR, vc.NGAYSINH, CURDATE()) BETWEEN 50 AND 59 THEN ''50-59''
                        ELSE ''60+''
                    END AS TIEUCHI 
                    FROM VIENCHUC vc
                    LEFT JOIN CO_CHUCVU ccv ON vc.MAVIENCHUC = ccv.MAVIENCHUC
                    LEFT JOIN COQUAN cq ON ccv.MACOQUAN = cq.MACOQUAN
                    LEFT JOIN CHUCVU cv ON ccv.MACHUCVU = cv.MACHUCVU
                    WHERE 1=1 ');
        IF p_Value IS NOT NULL AND p_Value <> '' THEN
            SET @sql = CONCAT(@sql, ' HAVING TIEUCHI = ''', p_Value, ''' ');
        END IF;

    ELSEIF p_Category = 'khenthuong' THEN
        SET @sql = CONCAT(@sql, ', htkt.TENHINHTHUCKHENTHUONG AS TIEUCHI, YEAR(dkt.NAMNHANKHENTHUONG) AS NAM 
                    FROM VIENCHUC vc
                    JOIN DUOC_KHENTHUONG dkt ON vc.MAVIENCHUC = dkt.MAVIENCHUC
                    JOIN HINHTHUCKHENTHUONG htkt ON dkt.MAHINHTHUCKHENTHUONG = htkt.MAHINHTHUCKHENTHUONG
                    LEFT JOIN CO_CHUCVU ccv ON vc.MAVIENCHUC = ccv.MAVIENCHUC
                    LEFT JOIN COQUAN cq ON ccv.MACOQUAN = cq.MACOQUAN
                    LEFT JOIN CHUCVU cv ON ccv.MACHUCVU = cv.MACHUCVU
                    WHERE 1=1 ');
        IF p_Value IS NOT NULL AND p_Value <> '' THEN
            SET @sql = CONCAT(@sql, ' AND (htkt.TENHINHTHUCKHENTHUONG LIKE ''%', p_Value, '%'' OR YEAR(dkt.NAMNHANKHENTHUONG) = ''', p_Value, ''') ');
        END IF;

    ELSEIF p_Category = 'kyluat' THEN
        SET @sql = CONCAT(@sql, ', htkl.TENHINHTHUCKYLUAT AS TIEUCHI, YEAR(bkl.NAMBIKYLUAT) AS NAM 
                    FROM VIENCHUC vc
                    JOIN BI_KYLUAT bkl ON vc.MAVIENCHUC = bkl.MAVIENCHUC
                    JOIN HINHTHUCKYLUAT htkl ON bkl.MAHINHTHUCKYLUAT = htkl.MAHINHTHUCKYLUAT
                    LEFT JOIN CO_CHUCVU ccv ON vc.MAVIENCHUC = ccv.MAVIENCHUC
                    LEFT JOIN COQUAN cq ON ccv.MACOQUAN = cq.MACOQUAN
                    LEFT JOIN CHUCVU cv ON ccv.MACHUCVU = cv.MACHUCVU
                    WHERE 1=1 ');
        IF p_Value IS NOT NULL AND p_Value <> '' THEN
            SET @sql = CONCAT(@sql, ' AND (htkl.TENHINHTHUCKYLUAT LIKE ''%', p_Value, '%'' OR YEAR(bkl.NAMBIKYLUAT) = ''', p_Value, ''') ');
        END IF;

    ELSEIF p_Category = 'gioitinh' THEN
        SET @sql = CONCAT(@sql, ', vc.GIOITINH AS TIEUCHI 
                    FROM VIENCHUC vc
                    LEFT JOIN CO_CHUCVU ccv ON vc.MAVIENCHUC = ccv.MAVIENCHUC
                    LEFT JOIN COQUAN cq ON ccv.MACOQUAN = cq.MACOQUAN
                    LEFT JOIN CHUCVU cv ON ccv.MACHUCVU = cv.MACHUCVU
                    WHERE 1=1 ');
        IF p_Value IS NOT NULL AND p_Value <> '' THEN
            SET @sql = CONCAT(@sql, ' AND vc.GIOITINH = ''', p_Value, ''' ');
        END IF;

    ELSEIF p_Category = 'coquan' THEN
        SET @sql = CONCAT(@sql, ', cq.TENCOQUAN AS TIEUCHI 
          FROM VIENCHUC vc
          LEFT JOIN CO_CHUCVU ccv ON vc.MAVIENCHUC = ccv.MAVIENCHUC
          LEFT JOIN COQUAN cq ON ccv.MACOQUAN = cq.MACOQUAN
          LEFT JOIN CHUCVU cv ON ccv.MACHUCVU = cv.MACHUCVU
          WHERE 1=1 ');
        IF p_Value IS NOT NULL AND p_Value <> '' THEN
            SET @sql = CONCAT(@sql, ' AND cq.TENCOQUAN LIKE ''%', p_Value, '%''');
        END IF;

    ELSEIF p_Category = 'trinhdo' THEN
        SET @sql = CONCAT(@sql, ', td.TENTRINHDO AS TIEUCHI 
          FROM VIENCHUC vc
          JOIN TRINHDO td ON vc.MATRINHDO = td.MATRINHDO
          LEFT JOIN CO_CHUCVU ccv ON vc.MAVIENCHUC = ccv.MAVIENCHUC
          LEFT JOIN COQUAN cq ON ccv.MACOQUAN = cq.MACOQUAN
          LEFT JOIN CHUCVU cv ON ccv.MACHUCVU = cv.MACHUCVU
          WHERE 1=1 ');
        IF p_Value IS NOT NULL AND p_Value <> '' THEN
            SET @sql = CONCAT(@sql, ' AND td.TENTRINHDO LIKE ''%', p_Value, '%''');
        END IF;

    ELSE
        SELECT 'We are fucked' AS ErrorMessage;
        SET @sql = NULL;
    END IF;

    IF @sql IS NOT NULL THEN
        PREPARE stmt FROM @sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END$$

DELIMITER ;