DELIMITER $$

CREATE DEFINER='root'@'%' PROCEDURE SP_CANHAN_THONGTIN()
BEGIN
    DECLARE v_ma CHAR(10);

    SELECT MAVIENCHUC
    INTO v_ma
    FROM USERS
    WHERE MAVIENCHUC = SUBSTRING_INDEX(USER(),'@',1);

    SELECT *
    FROM VW_LAY_DS_VIENCHUC
    WHERE MAVIENCHUC = v_ma;
END $$
DELIMITER ;


DELIMITER $$

CREATE DEFINER='root'@'%' PROCEDURE SP_VIENCHUC_LICHSU_CONGTAC()
BEGIN
    DECLARE v_ma CHAR(10);

    SELECT MAVIENCHUC
    INTO v_ma
    FROM USERS
    WHERE MAVIENCHUC = SUBSTRING_INDEX(USER(),'@',1);

    SELECT *
    FROM VW_DS_CONGTAC
    WHERE MAVIENCHUC = v_ma
    ORDER BY
        CASE
            WHEN THOIGIANKETTHUCCHUCVU IS NULL THEN 1
            ELSE 0
        END DESC,
        THOIGIANGIUCHUCVU DESC;
END $$

DELIMITER ;



DELIMITER $$

CREATE DEFINER='root'@'%' PROCEDURE SP_VIENCHUC_KHENTHUONG()
BEGIN
    DECLARE v_ma CHAR(10);

    SELECT MAVIENCHUC
    INTO v_ma
    FROM USERS
    WHERE MAVIENCHUC = SUBSTRING_INDEX(USER(),'@',1);

    SELECT
        htkt.TENHINHTHUCKHENTHUONG AS HINHTHUC_KHENTHUONG,
        dkt.NAMNHANKHENTHUONG AS NAM,
        dkt.SOQUYETDINHKHENTHUONG,
        dkt.NGUOIKYQUYETDINHKHENTHUONG
    FROM DUOC_KHENTHUONG dkt
    JOIN HINHTHUCKHENTHUONG htkt
        ON dkt.MAHINHTHUCKHENTHUONG = htkt.MAHINHTHUCKHENTHUONG
    WHERE dkt.MAVIENCHUC = v_ma
    ORDER BY dkt.NAMNHANKHENTHUONG DESC;
END $$

DELIMITER ;


DELIMITER $$

CREATE DEFINER='root'@'%' PROCEDURE SP_VIENCHUC_KYLUAT()
BEGIN
    DECLARE v_ma CHAR(10);

    SELECT MAVIENCHUC
    INTO v_ma
    FROM USERS
    WHERE MAVIENCHUC = SUBSTRING_INDEX(USER(),'@',1);

    SELECT
        htkl.TENHINHTHUCKYLUAT AS HINHTHUC_KYLUAT,
        bkl.NAMBIKYLUAT AS NAM,
        bkl.SOQUYETDINHKYLUAT,
        bkl.NGUOIKYQUYETDINHKYLUAT
    FROM BI_KYLUAT bkl
    JOIN HINHTHUCKYLUAT htkl
        ON bkl.MAHINHTHUCKYLUAT = htkl.MAHINHTHUCKYLUAT
    WHERE bkl.MAVIENCHUC = v_ma
    ORDER BY bkl.NAMBIKYLUAT DESC;
END $$

DELIMITER ;



-- * FULL Bộ trọn gói các bằng
DELIMITER $$

CREATE DEFINER='root'@'%' PROCEDURE SP_VIENCHUC_BANG()
BEGIN
    DECLARE v_ma CHAR(10);

    SELECT MAVIENCHUC
    INTO v_ma
    FROM USERS
    WHERE MAVIENCHUC = SUBSTRING_INDEX(USER(),'@',1);

    SELECT
        'CHUYENMON' AS LOAI,
        cm.TENCHUYENMON AS TEN
    FROM CO_TRDCM_CAONHAT ctcm
    JOIN CHUYENMON cm
        ON ctcm.MACHUYENMON = cm.MACHUYENMON
    WHERE ctcm.MAVIENCHUC = v_ma

    UNION ALL

    SELECT
        'NGOAINGU',
        nn.TENNGOAINGU
    FROM CO_TRD_NGOAINGU ctng
    JOIN NGOAINGU nn
        ON ctng.MANGOAINGU = nn.MANGOAINGU
    WHERE ctng.MAVIENCHUC = v_ma

    UNION ALL

    SELECT
        'TINHOC',
        th.CHUNGCHITINHOC
    FROM CO_TRD_TINHOC ctth
    JOIN CHUNGCHITINHOC th
        ON ctth.MACHUNGCHITINHOC = th.MACHUNGCHITINHOC
    WHERE ctth.MAVIENCHUC = v_ma;
END $$

DELIMITER ;


DELIMITER $$

CREATE DEFINER='root'@'%' PROCEDURE SP_VIENCHUC_DASHBOARD()
BEGIN
    DECLARE v_ma CHAR(10);

    SELECT MAVIENCHUC
    INTO v_ma
    FROM USERS
    WHERE MAVIENCHUC = SUBSTRING_INDEX(USER(),'@',1);

    SELECT *
    FROM VW_LAY_DS_VIENCHUC
    WHERE MAVIENCHUC = v_ma;

    SELECT *
    FROM VW_DS_CONGTAC
    WHERE MAVIENCHUC = v_ma;

    SELECT *
    FROM VW_KHENTHUONG
    WHERE MAVIENCHUC = v_ma;

    SELECT *
    FROM VW_KYLUAT
    WHERE MAVIENCHUC = v_ma;

END $$

DELIMITER ;