DELIMITER $$

CREATE PROCEDURE SP_CANHAN_THONGTIN(
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    SELECT *
    FROM VW_LAY_DS_VIENCHUC
    WHERE MAVIENCHUC = p_MAVIENCHUC;
END $$

DELIMITER ;


DELIMITER $$

CREATE PROCEDURE SP_VIENCHUC_LICHSU_CONGTAC(
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    SELECT *
    FROM VW_DS_CONGTAC
    WHERE MAVIENCHUC = p_MAVIENCHUC
    ORDER BY 
        CASE 
            WHEN THOIGIANKETTHUCCHUCVU IS NULL THEN 1 
            ELSE 0 
        END DESC,
        THOIGIANGIUCHUCVU DESC;
END $$
DELIMITER ;



DELIMITER $$

CREATE PROCEDURE SP_VIENCHUC_KHENTHUONG(
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    SELECT
        htkt.TENHINHTHUCKHENTHUONG AS HINHTHUC_KHENTHUONG,
        dkt.NAMNHANKHENTHUONG AS NAM,
        dkt.SOQUYETDINHKHENTHUONG,
        dkt.NGUOIKYQUYETDINHKHENTHUONG
    FROM DUOC_KHENTHUONG dkt
    JOIN HINHTHUCKHENTHUONG htkt
        ON dkt.MAHINHTHUCKHENTHUONG = htkt.MAHINHTHUCKHENTHUONG
    WHERE dkt.MAVIENCHUC = p_MAVIENCHUC
    ORDER BY dkt.NAMNHANKHENTHUONG DESC;
END $$

DELIMITER ;


DELIMITER $$

CREATE PROCEDURE SP_VIENCHUC_KYLUAT(
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    SELECT
        htkl.TENHINHTHUCKYLUAT AS HINHTHUC_KYLUAT,
        bkl.NAMBIKYLUAT AS NAM,
        bkl.SOQUYETDINHKYLUAT,
        bkl.NGUOIKYQUYETDINHKYLUAT
    FROM BI_KYLUAT bkl
    JOIN HINHTHUCKYLUAT htkl
        ON bkl.MAHINHTHUCKYLUAT = htkl.MAHINHTHUCKYLUAT
    WHERE bkl.MAVIENCHUC = p_MAVIENCHUC
    ORDER BY bkl.NAMBIKYLUAT DESC;
END $$

DELIMITER ;



-- FULL Bộ trọn gói các bằng
DELIMITER $$

CREATE PROCEDURE SP_VIENCHUC_BANG(
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    SELECT 
        'CHUYENMON' AS LOAI,
        cm.TENCHUYENMON AS TEN
    FROM CO_TRDCM_CAONHAT ctcm
    JOIN CHUYENMON cm ON ctcm.MACHUYENMON = cm.MACHUYENMON
    WHERE ctcm.MAVIENCHUC = p_MAVIENCHUC

    UNION ALL

    SELECT 
        'NGOAINGU',
        nn.TENNGOAINGU
    FROM CO_TRD_NGOAINGU ctng
    JOIN NGOAINGU nn ON ctng.MANGOAINGU = nn.MANGOAINGU
    WHERE ctng.MAVIENCHUC = p_MAVIENCHUC

    UNION ALL

    SELECT 
        'TINHOC',
        th.CHUNGCHITINHOC
    FROM CO_TRD_TINHOC ctth
    JOIN CHUNGCHITINHOC th ON ctth.MACHUNGCHITINHOC = th.MACHUNGCHITINHOC
    WHERE ctth.MAVIENCHUC = p_MAVIENCHUC;

END $$

DELIMITER ;


DELIMITER $$

CREATE PROCEDURE SP_VIENCHUC_DASHBOARD(
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    -- BASIC INFO
    SELECT * 
    FROM VW_LAY_DS_VIENCHUC
    WHERE MAVIENCHUC = p_MAVIENCHUC;

    -- WORK
    SELECT * 
    FROM VW_DS_CONGTAC
    WHERE MAVIENCHUC = p_MAVIENCHUC;

    -- REWARDS
    SELECT * 
    FROM VW_KHENTHUONG
    WHERE MAVIENCHUC = p_MAVIENCHUC;

    -- DISCIPLINE
    SELECT * 
    FROM VW_KYLUAT
    WHERE MAVIENCHUC = p_MAVIENCHUC;

END $$

DELIMITER ;