DELIMITER $$
CREATE TRIGGER TRG_CO_CHUCVU_BI
BEFORE INSERT ON CO_CHUCVU
FOR EACH ROW
BEGIN
    DECLARE v_count INT DEFAULT 0;

    -- * End date > start date
    IF NEW.THOIGIANKETTHUCCHUCVU IS NOT NULL
       AND NEW.THOIGIANKETTHUCCHUCVU < NEW.THOIGIANGIUCHUCVU THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'THOIGIANKETTHUCCHUCVU >= THOIGIANGIUCHUCVU';
    END IF;

    -- * Only one active position allowed
    IF NEW.THOIGIANKETTHUCCHUCVU IS NULL THEN

        SELECT COUNT(*)
        INTO v_count
        FROM CO_CHUCVU
        WHERE MAVIENCHUC = NEW.MAVIENCHUC
          AND THOIGIANKETTHUCCHUCVU IS NULL;

        IF v_count > 0 THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Vien chuc hien tai da co chuc vu';
        END IF;

    END IF;

    -- * No overlapping periods
    SELECT COUNT(*)
    INTO v_count
    FROM CO_CHUCVU
    WHERE MAVIENCHUC = NEW.MAVIENCHUC
      AND (
            COALESCE(NEW.THOIGIANKETTHUCCHUCVU,'9999-12-31')
                >= THOIGIANGIUCHUCVU
        AND
            COALESCE(THOIGIANKETTHUCCHUCVU,'9999-12-31')
                >= NEW.THOIGIANGIUCHUCVU
      );

    IF v_count > 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'thoi gian giu chuc vu trung lap';
    END IF;

END$$

-- ! TRIGGER TRG_CO_CHUCVU_BU

CREATE TRIGGER TRG_CO_CHUCVU_BU
BEFORE UPDATE ON CO_CHUCVU
FOR EACH ROW
BEGIN
    DECLARE v_count INT DEFAULT 0;

    -- * End date > start date
    IF NEW.THOIGIANKETTHUCCHUCVU IS NOT NULL
       AND NEW.THOIGIANKETTHUCCHUCVU < NEW.THOIGIANGIUCHUCVU THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'THOIGIANKETTHUCCHUCVU >= THOIGIANGIUCHUCVU';
    END IF;

    -- * chi 1 chuc vu 1 lan
    IF NEW.THOIGIANKETTHUCCHUCVU IS NULL THEN

        SELECT COUNT(*)
        INTO v_count
        FROM CO_CHUCVU
        WHERE MAVIENCHUC = NEW.MAVIENCHUC
          AND THOIGIANKETTHUCCHUCVU IS NULL
          AND NOT (
                MAVIENCHUC = OLD.MAVIENCHUC
            AND MACHUCVU = OLD.MACHUCVU
            AND MACOQUAN = OLD.MACOQUAN
            AND MANGHENGHIEP = OLD.MANGHENGHIEP
          );

        IF v_count > 0 THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Vien chuc da co chuc vu';
        END IF;

    END IF;

    -- * No overlapping periods
    SELECT COUNT(*)
    INTO v_count
    FROM CO_CHUCVU
    WHERE MAVIENCHUC = NEW.MAVIENCHUC
      AND NOT (
            MAVIENCHUC = OLD.MAVIENCHUC
        AND MACHUCVU = OLD.MACHUCVU
        AND MACOQUAN = OLD.MACOQUAN
        AND MANGHENGHIEP = OLD.MANGHENGHIEP
      )
      AND (
            COALESCE(NEW.THOIGIANKETTHUCCHUCVU,'9999-12-31')
                >= THOIGIANGIUCHUCVU
        AND
            COALESCE(THOIGIANKETTHUCCHUCVU,'9999-12-31')
                >= NEW.THOIGIANGIUCHUCVU
      );

    IF v_count > 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Chuc vu bi trung lap';
    END IF;

END$$

DELIMITER ;



DELIMITER $$

CREATE TRIGGER TRG_THUOC_QUANDOI_BI
BEFORE INSERT ON THUOC_QUANDOI
FOR EACH ROW
BEGIN
    IF NEW.NGAYXUATNGU IS NOT NULL
       AND NEW.NGAYXUATNGU < NEW.NGAYNHAPNGU THEN

        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ngay xuat ngu phai sau ngay nhap ngu';

    END IF;
END$$

CREATE TRIGGER TRG_THUOC_QUANDOI_BU
BEFORE UPDATE ON THUOC_QUANDOI
FOR EACH ROW
BEGIN
    IF NEW.NGAYXUATNGU IS NOT NULL
       AND NEW.NGAYXUATNGU < NEW.NGAYNHAPNGU THEN

        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ngay xuat ngu phai sau ngay nhap ngu';

    END IF;
END$$

DELIMITER ;

DELIMITER $$

CREATE TRIGGER TRG_TCDT_CTXH_BI
BEFORE INSERT ON THUOC_TOCHUCDOANTHECHINHTRIXAHOI
FOR EACH ROW
BEGIN
    IF NEW.NGAYCHINHTHUC IS NOT NULL
       AND NEW.NGAYCHINHTHUC < NEW.NGAYVAOTOCHUC THEN

        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ngay chinh thuc phai sau ngay vao to chuc';

    END IF;
END$$

CREATE TRIGGER TRG_TCDT_CTXH_BU
BEFORE UPDATE ON THUOC_TOCHUCDOANTHECHINHTRIXAHOI
FOR EACH ROW
BEGIN
    IF NEW.NGAYCHINHTHUC IS NOT NULL
       AND NEW.NGAYCHINHTHUC < NEW.NGAYVAOTOCHUC THEN

        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ngay chinh thuc phai sau ngay vao to chuc';

    END IF;
END$$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER TRG_CO_TINHTRANGSK_BI
BEFORE INSERT ON CO_TINHTRANGSK
FOR EACH ROW
BEGIN

    IF NEW.CANNANG <= 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Can nang khong hop le';
    END IF;

    IF NEW.CHIEUCAO <= 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Chieu cao khong hop le';
    END IF;

    IF NEW.CANNANG < 40 OR NEW.CANNANG > 150 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Can nang ngoai pham vi cho phep';
    END IF;

    IF NEW.CHIEUCAO < 100 OR NEW.CHIEUCAO > 250 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Chieu cao ngoai pham vi cho phep';
    END IF;

END$$

CREATE TRIGGER TRG_CO_TINHTRANGSK_BU
BEFORE UPDATE ON CO_TINHTRANGSK
FOR EACH ROW
BEGIN

    IF NEW.CANNANG <= 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Can nang khong hop le';
    END IF;

    IF NEW.CHIEUCAO <= 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Chieu cao khong hop le';
    END IF;

END$$

DELIMITER ;



DELIMITER $$

CREATE TRIGGER TRG_DUOC_KHENTHUONG_BI
BEFORE INSERT ON DUOC_KHENTHUONG
FOR EACH ROW
BEGIN
    DECLARE v_ngaytuyendung DATETIME;

    SELECT NGAYTUYENDUNG
    INTO v_ngaytuyendung
    FROM VIENCHUC
    WHERE MAVIENCHUC = NEW.MAVIENCHUC;

    IF NEW.NAMNHANKHENTHUONG < v_ngaytuyendung THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Khen thuong truoc ngay tuyen dung';
    END IF;
END$$

DELIMITER ;



DELIMITER $$

CREATE TRIGGER TRG_BI_KYLUAT_BI
BEFORE INSERT ON BI_KYLUAT
FOR EACH ROW
BEGIN
    DECLARE v_ngaytuyendung DATETIME;

    SELECT NGAYTUYENDUNG
    INTO v_ngaytuyendung
    FROM VIENCHUC
    WHERE MAVIENCHUC = NEW.MAVIENCHUC;

    IF NEW.NAMBIKYLUAT < v_ngaytuyendung THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ky luat truoc ngay tuyen dung';
    END IF;
END$$

DELIMITER ;



DELIMITER $$

CREATE TRIGGER TRG_TUYENDUNG_BI
BEFORE INSERT ON TUYENDUNG
FOR EACH ROW
BEGIN
    DECLARE v_ngaysinh DATETIME;

    SELECT NGAYSINH
    INTO v_ngaysinh
    FROM VIENCHUC
    WHERE MAVIENCHUC = NEW.MAVIENCHUC;

    IF NEW.NGAYTUYENDUNG < v_ngaysinh THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ngay tuyen dung khong hop le';
    END IF;

    IF TIMESTAMPDIFF(YEAR,v_ngaysinh,NEW.NGAYTUYENDUNG) < 18 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Vien chuc phai du 18 tuoi';
    END IF;
END$$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER TRG_VIENCHUC_BI
BEFORE INSERT ON VIENCHUC
FOR EACH ROW
BEGIN

    IF NEW.NGAYSINH > NOW() THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ngay sinh khong hop le';
    END IF;

    IF NEW.NGAYTUYENDUNG < NEW.NGAYSINH THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ngay tuyen dung phai sau ngay sinh';
    END IF;

    IF TIMESTAMPDIFF(YEAR, NEW.NGAYSINH, NEW.NGAYTUYENDUNG) < 18 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Vien chuc phai du 18 tuoi';
    END IF;

END$$

CREATE TRIGGER TRG_VIENCHUC_BU
BEFORE UPDATE ON VIENCHUC
FOR EACH ROW
BEGIN

    IF NEW.NGAYTUYENDUNG < NEW.NGAYSINH THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ngay tuyen dung phai sau ngay sinh';
    END IF;

END$$

DELIMITER ;

--   !  TRIGGER FOR LOG

DELIMITER $$

CREATE TRIGGER TR_VIENCHUC_AI
AFTER INSERT ON VIENCHUC
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG
    (
        TABLE_NAME,
        RECORD_ID,
        ACTION_TYPE,
        OLD_DATA,
        NEW_DATA,
        UPDATED_BY
    )
    VALUES
    (
        'VIENCHUC',
        NEW.MAVIENCHUC,
        'INSERT',
        NULL,

        JSON_OBJECT(
            'MAVIENCHUC', NEW.MAVIENCHUC,
            'HO', NEW.HO,
            'TENLOT', NEW.TENLOT,
            'TEN', NEW.TEN
        ),

        CURRENT_USER()
    );
END$$

DELIMITER ;

DELIMITER $$

CREATE TRIGGER TR_VIENCHUC_AU
AFTER UPDATE ON VIENCHUC
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG
    (
        TABLE_NAME,
        RECORD_ID,
        ACTION_TYPE,
        OLD_DATA,
        NEW_DATA,
        UPDATED_BY
    )
    VALUES
    (
        'VIENCHUC',
        NEW.MAVIENCHUC,
        'UPDATE',

        JSON_OBJECT(
            'MAVIENCHUC', OLD.MAVIENCHUC,
            'HO', OLD.HO,
            'TENLOT', OLD.TENLOT,
            'TEN', OLD.TEN
        ),

        JSON_OBJECT(
            'MAVIENCHUC', NEW.MAVIENCHUC,
            'HO', NEW.HO,
            'TENLOT', NEW.TENLOT,
            'TEN', NEW.TEN
        ),

        CURRENT_USER()
    );
END$$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER TR_VIENCHUC_AD
AFTER DELETE ON VIENCHUC
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG
    (
        TABLE_NAME,
        RECORD_ID,
        ACTION_TYPE,
        OLD_DATA,
        NEW_DATA,
        UPDATED_BY
    )
    VALUES
    (
        'VIENCHUC',
        OLD.MAVIENCHUC,
        'DELETE',

        JSON_OBJECT(
            'MAVIENCHUC', OLD.MAVIENCHUC,
            'HO', OLD.HO,
            'TENLOT', OLD.TENLOT,
            'TEN', OLD.TEN
        ),

        NULL,

        CURRENT_USER()
    );
END$$

DELIMITER ;

-- ! 