CREATE ROLE 'admin_role';
CREATE ROLE 'hr_role';
CREATE ROLE 'vienchuc_role';
CREATE ROLE 'viewer_role';

GRANT ALL PRIVILEGES ON *.* TO 'admin_role' WITH GRANT OPTION;

-- Employee management views
GRANT SELECT ON VW_LAY_DS_VIENCHUC TO 'hr_role';
GRANT SELECT ON VW_DS_CONGTAC TO 'hr_role';
GRANT SELECT ON VW_ThongKeNhanSu TO 'hr_role';
GRANT SELECT ON VW_KHENTHUONG TO 'hr_role';
GRANT SELECT ON VW_KYLUAT TO 'hr_role';

-- Statistics views
GRANT SELECT ON VW_THONGKE_GIOITINH TO 'hr_role';
GRANT SELECT ON VW_THONGKE_DANTOC TO 'hr_role';
GRANT SELECT ON VW_THONGKE_TONGIAO TO 'hr_role';
GRANT SELECT ON VW_THONGKE_DOTUOI TO 'hr_role';
GRANT SELECT ON VW_THONGKE_TRINHDOHOCVAN TO 'hr_role';
GRANT SELECT ON VW_THONGKE_CHUYENMON TO 'hr_role';
GRANT SELECT ON VW_THONGKE_NGOAINGU TO 'hr_role';
GRANT SELECT ON VW_THONGKE_TINHOC TO 'hr_role';
GRANT SELECT ON VW_THONGKE_COQUAN TO 'hr_role';
GRANT SELECT ON VW_THONGKE_CHUCVU TO 'hr_role';
GRANT SELECT ON VW_THONGKE_NGHENGHIEP TO 'hr_role';
GRANT SELECT ON VW_THONGKE_KHENTHUONG TO 'hr_role';
GRANT SELECT ON VW_THONGKE_KYLUAT TO 'hr_role';
GRANT SELECT ON VW_THONGKE_KHENTHUONG_THEONAM TO 'hr_role';
GRANT SELECT ON VW_THONGKE_KYLUAT_THEONAM TO 'hr_role';
GRANT SELECT ON VW_THONGKE_TUYENDUNG_THEONAM TO 'hr_role';
GRANT SELECT ON VW_DASHBOARD_TONGQUAN TO 'hr_role';
GRANT SELECT ON VW_THONGKE_TINHTRANGSUCKHOE TO 'hr_role';

-- Execute all management procedures
GRANT EXECUTE ON PROCEDURE SP_THEM_VIENCHUC TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_VIENCHUC TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_VIENCHUC TO 'hr_role';

GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_DUOC_KHENTHUONG TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_DUOC_KHENTHUONG TO 'hr_role';

GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_BI_KYLUAT TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_BI_KYLUAT TO 'hr_role';

-- Continue granting EXECUTE on all SP_CAPNHAT_* and SP_XOA_* procedures

GRANT SELECT ON VW_THONGKE_GIOITINH TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_DANTOC TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_TONGIAO TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_DOTUOI TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_TRINHDOHOCVAN TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_CHUYENMON TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_NGOAINGU TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_TINHOC TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_COQUAN TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_CHUCVU TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_NGHENGHIEP TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_KHENTHUONG TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_KYLUAT TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_KHENTHUONG_THEONAM TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_KYLUAT_THEONAM TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_TUYENDUNG_THEONAM TO 'viewer_role';
GRANT SELECT ON VW_DASHBOARD_TONGQUAN TO 'viewer_role';
GRANT SELECT ON VW_THONGKE_TINHTRANGSUCKHOE TO 'viewer_role';

-- VIEN CHUC

GRANT EXECUTE ON PROCEDURE SP_CANHAN_THONGTIN TO 'vienchuc_role';
GRANT EXECUTE ON PROCEDURE SP_VIENCHUC_LICHSU_CONGTAC TO 'vienchuc_role';
GRANT EXECUTE ON PROCEDURE SP_VIENCHUC_KHENTHUONG TO 'vienchuc_role';
GRANT EXECUTE ON PROCEDURE SP_VIENCHUC_KYLUAT TO 'vienchuc_role';
GRANT EXECUTE ON PROCEDURE SP_VIENCHUC_BANG TO 'vienchuc_role';
GRANT EXECUTE ON PROCEDURE SP_VIENCHUC_DASHBOARD TO 'vienchuc_role';