CREATE ROLE 'admin_role';
CREATE ROLE 'hr_role';
CREATE ROLE 'vienchuc_role';
CREATE ROLE 'thanhtra_role';

GRANT ALL PRIVILEGES ON *.* TO 'admin_role' WITH GRANT OPTION;


-- ! VIENCHUC

GRANT EXECUTE ON PROCEDURE SP_CANHAN_THONGTIN
TO 'vienchuc_role';

GRANT EXECUTE ON PROCEDURE SP_VIENCHUC_LICHSU_CONGTAC
TO 'vienchuc_role';

GRANT EXECUTE ON PROCEDURE SP_VIENCHUC_KHENTHUONG
TO 'vienchuc_role';

GRANT EXECUTE ON PROCEDURE SP_VIENCHUC_KYLUAT
TO 'vienchuc_role';

GRANT EXECUTE ON PROCEDURE SP_VIENCHUC_BANG
TO 'vienchuc_role';

GRANT EXECUTE ON PROCEDURE SP_VIENCHUC_DASHBOARD
TO 'vienchuc_role';

-- ! HR

GRANT 'vienchuc_role' TO 'hr_role';
GRANT SELECT ON VW_LAY_DS_VIENCHUC TO 'hr_role';

GRANT SELECT ON VW_DS_CONGTAC TO 'hr_role';

GRANT SELECT ON VW_ThongKeNhanSu TO 'hr_role';

GRANT SELECT ON VW_KHENTHUONG TO 'hr_role';

GRANT SELECT ON VW_KYLUAT TO 'hr_role';


--   ! CRUD STUFF

GRANT EXECUTE ON PROCEDURE SP_THEM_VIENCHUC
TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_VIENCHUC TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_VIENCHUC TO 'hr_role';

GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_DUOC_KHENTHUONG TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_DUOC_KHENTHUONG TO 'hr_role';

GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_BI_KYLUAT TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_BI_KYLUAT TO 'hr_role';

GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_MADANHHIEU TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_MATONGIAO TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_MAHOCHAM TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_MATRINHDO TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_MAHANGTHUONGBINH TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_MAXAPHUONG TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_XAP_MAXAPHUONG TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_HO TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_TENLOT TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_TEN TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_TENKHAC TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_GIOITINH TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_NGAYTUYENDUNG TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_SOHIEUVIENCHUC TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_ANHDAIDIEN TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_SOBAOHIEM TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_NAMDUOCPHONGHOCHAM TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_NAMDUOCPHONGDANHHIEU TO 'hr_role';

GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_CO_CAPLYLUANCHINHTRI TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_CO_CAPLYLUANCHINHTRI TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_CO_CAPQUANLYNHANUOC TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_CO_CAPQUANLYNHANUOC TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_CO_CHUCVU TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_CO_CHUCVU TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_CO_HESOLUONG TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_CO_HESOLUONG TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_CO_HOKHAUTHUONGTRU TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_CO_HOKHAUTHUONGTRU TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_CO_TAMTRU TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_CO_TAMTRU TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_CO_TINHTRANGSK TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_CO_TINHTRANGSK TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_CO_TRDCM_CAONHAT TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_CO_TRDCM_CAONHAT TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_CO_TRD_NGOAINGU TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_CO_TRD_NGOAINGU TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_CO_TRD_TINHOC TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_CO_TRD_TINHOC TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_THUOC_QUANDOI TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_THUOC_QUANDOI TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_THUOC_TCDT_CTXH TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_THUOC_TCDT_CTXH TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_TUYENDUNG TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_TUYENDUNG TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_XAPHUONG TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_XAPHUONG TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_CAPNHAT_THUOC_NHOMNGACH TO 'hr_role';
GRANT EXECUTE ON PROCEDURE SP_XOA_NHOMNGACH TO 'hr_role';

-- ! Thanh tra role

GRANT SELECT ON VW_ThongKeNhanSu TO 'thanhtra_role';

