-- 1. Setup
SET FOREIGN_KEY_CHECKS = 0;
CREATE DATABASE IF NOT EXISTS CSDL_VIEN_CHUC;
USE CSDL_VIEN_CHUC;

-- 2. Drop tables in order to avoid foreign key errors
DROP TABLE IF EXISTS BACLUONG;
DROP TABLE IF EXISTS BI_KYLUAT;
DROP TABLE IF EXISTS CAPLYLUANCHINHTRI;
DROP TABLE IF EXISTS CAPQUANLYNHANUOC;
DROP TABLE IF EXISTS CHITIETLUONG;
DROP TABLE IF EXISTS CHUCDANH_NGHENGHIEP;
DROP TABLE IF EXISTS CHUCVU;
DROP TABLE IF EXISTS CHUNGCHITINHOC;
DROP TABLE IF EXISTS CHUYENMON;
DROP TABLE IF EXISTS COQUAN;
DROP TABLE IF EXISTS CO_CAPLYLUANCHINHTRI;
DROP TABLE IF EXISTS CO_CAPQUANLYNHANUOC;
DROP TABLE IF EXISTS CO_CHUCVU;
DROP TABLE IF EXISTS CO_HESOLUONG;
DROP TABLE IF EXISTS CO_HOKHAUTHUONGTRU;
DROP TABLE IF EXISTS CO_TAMTRU;
DROP TABLE IF EXISTS CO_TINHTRANGSK;
DROP TABLE IF EXISTS CO_TRDCM_CAONHAT;
DROP TABLE IF EXISTS CO_TRD_NGOAINGU;
DROP TABLE IF EXISTS CO_TRD_TINHOC;
DROP TABLE IF EXISTS DANHHIEU;
DROP TABLE IF EXISTS DANTOC;
DROP TABLE IF EXISTS DUOC_KHENTHUONG;
DROP TABLE IF EXISTS HANGTHUONGBINH;
DROP TABLE IF EXISTS HINHTHUCKHENTHUONG;
DROP TABLE IF EXISTS HINHTHUCKYLUAT;
DROP TABLE IF EXISTS HOCHAM;
DROP TABLE IF EXISTS NGOAINGU;
DROP TABLE IF EXISTS NHOMNGACH;
DROP TABLE IF EXISTS QUANHAM;
DROP TABLE IF EXISTS THONGTINQUANDOI;
DROP TABLE IF EXISTS THUOC_NHOM_NGACH;
DROP TABLE IF EXISTS THUOC_QUANDOI;
DROP TABLE IF EXISTS THUOC_TOCHUCDOANTHECHINHTRIXAHOI;
DROP TABLE IF EXISTS TINHTHANH;
DROP TABLE IF EXISTS TINHTRANGSUCKHOE;
DROP TABLE IF EXISTS TOCHUCDOANTHECHINHTRIXAHOI;
DROP TABLE IF EXISTS TONGIAO;
DROP TABLE IF EXISTS TRINHDOHOCVAN;
DROP TABLE IF EXISTS TUYENDUNG;
DROP TABLE IF EXISTS VIENCHUC;
DROP TABLE IF EXISTS XAPHUONG;

SET FOREIGN_KEY_CHECKS = 0;

-- 1. Master Tables (No dependencies)
CREATE TABLE BACLUONG (MABACLUONG CHAR(5) NOT NULL, PRIMARY KEY (MABACLUONG)) ENGINE=InnoDB;
CREATE TABLE CAPLYLUANCHINHTRI (MACAPCT CHAR(5) NOT NULL, TENCAPCT VARCHAR(30), PRIMARY KEY (MACAPCT)) ENGINE=InnoDB;
CREATE TABLE CAPQUANLYNHANUOC (MACAPQLNN CHAR(5) NOT NULL, TENCAPQLNN VARCHAR(30), PRIMARY KEY (MACAPQLNN)) ENGINE=InnoDB;
CREATE TABLE CHITIETLUONG (MACHITIETLUONG CHAR(5) NOT NULL, PRIMARY KEY (MACHITIETLUONG)) ENGINE=InnoDB;
CREATE TABLE CHUCDANH_NGHENGHIEP (MANGHENGHIEP CHAR(5) NOT NULL, TENNGHENGHIEP VARCHAR(30), PRIMARY KEY (MANGHENGHIEP)) ENGINE=InnoDB;
CREATE TABLE CHUCVU (MACHUCVU CHAR(5) NOT NULL, TENCHUCVU CHAR(30), PRIMARY KEY (MACHUCVU)) ENGINE=InnoDB;
CREATE TABLE CHUNGCHITINHOC (MACHUNGCHITINHOC CHAR(5) NOT NULL, CHUNGCHITINHOC VARCHAR(30), PRIMARY KEY (MACHUNGCHITINHOC)) ENGINE=InnoDB;
CREATE TABLE CHUYENMON (MACHUYENMON CHAR(5) NOT NULL, TENCHUYENMON VARCHAR(30), PRIMARY KEY (MACHUYENMON)) ENGINE=InnoDB;
CREATE TABLE COQUAN (MACOQUAN CHAR(5) NOT NULL, TENCOQUAN VARCHAR(30), PRIMARY KEY (MACOQUAN)) ENGINE=InnoDB;
CREATE TABLE DANHHIEU (MADANHHIEU CHAR(5) NOT NULL, TENDANHHIEU VARCHAR(30), PRIMARY KEY (MADANHHIEU)) ENGINE=InnoDB;
CREATE TABLE DANTOC (MADANTOC CHAR(5) NOT NULL, TENDANTOC VARCHAR(30), PRIMARY KEY (MADANTOC)) ENGINE=InnoDB;
CREATE TABLE HANGTHUONGBINH (MAHANGTHUONGBINH CHAR(5) NOT NULL, TENHANGTHUONGBINH VARCHAR(30), PRIMARY KEY (MAHANGTHUONGBINH)) ENGINE=InnoDB;
CREATE TABLE HINHTHUCKHENTHUONG (MAHINHTHUCKHENTHUONG CHAR(5) NOT NULL, TENHINHTHUCKHENTHUONG VARCHAR(30), PRIMARY KEY (MAHINHTHUCKHENTHUONG)) ENGINE=InnoDB;
CREATE TABLE HINHTHUCKYLUAT (MAHINHTHUCKYLUAT CHAR(5) NOT NULL, TENHINHTHUCKYLUAT CHAR(30), PRIMARY KEY (MAHINHTHUCKYLUAT)) ENGINE=InnoDB;
CREATE TABLE HOCHAM (MAHOCHAM CHAR(5) NOT NULL, TENHOCHAM VARCHAR(30), PRIMARY KEY (MAHOCHAM)) ENGINE=InnoDB;
CREATE TABLE NGOAINGU (MANGOAINGU CHAR(5) NOT NULL, TENNGOAINGU VARCHAR(30), CAPDO CHAR(5), PRIMARY KEY (MANGOAINGU)) ENGINE=InnoDB;
CREATE TABLE NHOMNGACH (MANHOMNGACH CHAR(4) NOT NULL, TENNHOMNGACH CHAR(30), PRIMARY KEY (MANHOMNGACH)) ENGINE=InnoDB;
CREATE TABLE QUANHAM (MAQUANHAM CHAR(5) NOT NULL, TENQUANHAM VARCHAR(30), PRIMARY KEY (MAQUANHAM)) ENGINE=InnoDB;
CREATE TABLE THONGTINQUANDOI (MATTD_QD CHAR(5) NOT NULL, PRIMARY KEY (MATTD_QD)) ENGINE=InnoDB;
CREATE TABLE TINHTHANH (MATINHTHANH CHAR(5) NOT NULL, TENTINHTHANH VARCHAR(30), PRIMARY KEY (MATINHTHANH)) ENGINE=InnoDB;
CREATE TABLE TINHTRANGSUCKHOE (MASUCKHOE CHAR(5) NOT NULL, TINHTRANGSUCKHOE VARCHAR(20), PRIMARY KEY (MASUCKHOE)) ENGINE=InnoDB;
CREATE TABLE TOCHUCDOANTHECHINHTRIXAHOI (MATOCHUCDTCTXH CHAR(5) NOT NULL, TENTOCHUCDTCTXH TEXT, PRIMARY KEY (MATOCHUCDTCTXH)) ENGINE=InnoDB;
CREATE TABLE TONGIAO (MATONGIAO CHAR(5) NOT NULL, TENTONGIAO VARCHAR(30), PRIMARY KEY (MATONGIAO)) ENGINE=InnoDB;
CREATE TABLE TRINHDOHOCVAN (MATRINHDO CHAR(5) NOT NULL, TRINHDOGIAODUCPHOTHONG CHAR(5), TRINHDONGHIEPVUCHUYENNGANH VARCHAR(100), PRIMARY KEY (MATRINHDO)) ENGINE=InnoDB;
CREATE TABLE XAPHUONG (MAXAPHUONG CHAR(5) NOT NULL, MATINHTHANH CHAR(5) NOT NULL, TENXAPHUONG VARCHAR(30), PRIMARY KEY (MAXAPHUONG), FOREIGN KEY (MATINHTHANH) REFERENCES TINHTHANH(MATINHTHANH)) ENGINE=InnoDB;

-- 2. Dependent Tables
CREATE TABLE VIENCHUC (
   MAVIENCHUC CHAR(10) NOT NULL, MADANHHIEU CHAR(5), MATONGIAO CHAR(5), MAHOCHAM CHAR(5), MATRINHDO CHAR(5) NOT NULL, MADANTOC CHAR(5) NOT NULL, MAHANGTHUONGBINH CHAR(5), MAXAPHUONG CHAR(5) NOT NULL, XAP_MAXAPHUONG CHAR(5) NOT NULL, HO VARCHAR(20), TENLOT VARCHAR(40), TEN VARCHAR(20), TENKHAC VARCHAR(100), NGAYSINH DATETIME, GIOITINH VARCHAR(3), NGAYTUYENDUNG DATETIME, SOHIEUVIENCHUC CHAR(10), ANHDAIDIEN TEXT, SOCCCD CHAR(10), NOICAPCCCD CHAR(100), NGAYCAPCCCD DATETIME, SOBAOHIEM CHAR(10), NHOMMAU CHAR(3), NAMDUOCPHONGHOCHAM DATETIME, NAMDUOCPHONGDANHHIEU DATETIME,
   PRIMARY KEY (MAVIENCHUC)
) ENGINE=InnoDB;

CREATE TABLE BI_KYLUAT (MAHINHTHUCKYLUAT CHAR(5) NOT NULL, MAVIENCHUC CHAR(10) NOT NULL, NAMBIKYLUAT DATETIME, SOQUYETDINHKYLUAT CHAR(50), NGUOIKYQUYETDINHKYLUAT CHAR(150), PRIMARY KEY (MAHINHTHUCKYLUAT, MAVIENCHUC), FOREIGN KEY (MAHINHTHUCKYLUAT) REFERENCES HINHTHUCKYLUAT(MAHINHTHUCKYLUAT), FOREIGN KEY (MAVIENCHUC) REFERENCES VIENCHUC(MAVIENCHUC)) ENGINE=InnoDB;

CREATE TABLE CO_CAPLYLUANCHINHTRI (MACAPCT CHAR(5) NOT NULL, MAVIENCHUC CHAR(10) NOT NULL, PRIMARY KEY (MACAPCT, MAVIENCHUC), FOREIGN KEY (MACAPCT) REFERENCES CAPLYLUANCHINHTRI(MACAPCT), FOREIGN KEY (MAVIENCHUC) REFERENCES VIENCHUC(MAVIENCHUC)) ENGINE=InnoDB;

CREATE TABLE CO_CAPQUANLYNHANUOC (MACAPQLNN CHAR(5) NOT NULL, MAVIENCHUC CHAR(10) NOT NULL, PRIMARY KEY (MACAPQLNN, MAVIENCHUC), FOREIGN KEY (MACAPQLNN) REFERENCES CAPQUANLYNHANUOC(MACAPQLNN), FOREIGN KEY (MAVIENCHUC) REFERENCES VIENCHUC(MAVIENCHUC)) ENGINE=InnoDB;

-- Note: Continue the rest of your linkage tables (CO_CHUCVU, DUOC_KHENTHUONG, etc.) using the same pattern.

SET FOREIGN_KEY_CHECKS = 1;