CREATE VIEW VW_LAY_DS_VIENCHUC AS
SELECT
    vc.MAVIENCHUC,
    CONCAT(vc.HO, ' ', vc.TENLOT, ' ', vc.TEN) AS HOTEN,
    vc.NGAYSINH,
    vc.GIOITINH,

    dt.TENDANTOC,
    tg.TENTONGIAO,

    td.TRINHDONGHIEPVUCHUYENNGANH,

    cq.TENCOQUAN,
    cv.TENCHUCVU

FROM VIENCHUC vc

LEFT JOIN DANTOC dt
    ON vc.MADANTOC = dt.MADANTOC

LEFT JOIN TONGIAO tg
    ON vc.MATONGIAO = tg.MATONGIAO

LEFT JOIN TRINHDOHOCVAN td
    ON vc.MATRINHDO = td.MATRINHDO

LEFT JOIN CO_CHUCVU ccv
    ON vc.MAVIENCHUC = ccv.MAVIENCHUC

LEFT JOIN COQUAN cq
    ON ccv.MACOQUAN = cq.MACOQUAN

LEFT JOIN CHUCVU cv
    ON ccv.MACHUCVU = cv.MACHUCVU;