DELIMITER $$

CREATE PROCEDURE SP_TRUYXUAT_CHITIET_VIENCHUC (
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    SELECT 
        -- Thông tin cá nhân
        vc.MAVIENCHUC,
        CONCAT(vc.HO, ' ', vc.TENLOT, ' ', vc.TEN) AS HOTEN,
        vc.TENKHAC,
        vc.NGAYSINH,
        vc.GIOITINH,
        vc.SOCCCD,
        vc.NGAYTUYENDUNG,
        vc.SOHIEUVIENCHUC,
        dt.TENDANTOC,
        tg.TENTONGIAO,
        hh.TENHOCHAM,
        dd.TENDANHHIEU,
        
        --   Ngạch lương
        tnn.MACHITIETLUONG,
        tnn.THOIGIANBATDAUHUONG,
        hsl.MANHOMNGACH,
        nn.TENNHOMNGACH,
        hsl.MABACLUONG,
        hsl.HESOLUONG,

        --   Khen thưởng
        kt.SOQUYETDINHKHENTHUONG,
        kt.NAMNHANKHENTHUONG,
        hckt.TENHINHTHUCKHENTHUONG,
        
        --  Kỷ luật
        kl.SOQUYETDINHKYLUAT,
        kl.NAMBIKYLUAT,
        hckl.TENHINHTHUCKYLUAT

    FROM VIENCHUC vc
    --  nối lý lịch
    LEFT JOIN DANTOC dt ON vc.MADANTOC = dt.MADANTOC
    LEFT JOIN TONGIAO tg ON vc.MATONGIAO = tg.MATONGIAO
    LEFT JOIN HOCHAM hh ON vc.MAHOCHAM = hh.MAHOCHAM
    LEFT JOIN DANHHIEU dd ON vc.MADANHHIEU = dd.MADANHHIEU
    
    --  nối Lương lẹo
    LEFT JOIN THUOC_NHOM_NGACH tnn ON vc.MAVIENCHUC = tnn.MAVIENCHUC
    LEFT JOIN CO_HESOLUONG hsl ON tnn.MACHITIETLUONG = hsl.MACHITIETLUONG
    LEFT JOIN NHOMNGACH nn ON hsl.MANHOMNGACH = nn.MANHOMNGACH
    
    --  nối Khen thưởng
    LEFT JOIN DUOC_KHENTHUONG kt ON vc.MAVIENCHUC = kt.MAVIENCHUC
    LEFT JOIN HINHTHUCKHENTHUONG hckt ON kt.MAHINHTHUCKHENTHUONG = hckt.MAHINHTHUCKHENTHUONG
    
    --  nối Kỷ luật
    LEFT JOIN BI_KYLUAT kl ON vc.MAVIENCHUC = kl.MAVIENCHUC
    LEFT JOIN HINHTHUCKYLUAT hckl ON kl.MAHINHTHUCKYLUAT = hckl.MAHINHTHUCKYLUAT
    
    WHERE vc.MAVIENCHUC = p_MAVIENCHUC;
END$$

DELIMITER ;



DELIMITER $$
-- DÀI VCL!!!!!
CREATE PROCEDURE SP_CAPNHAT_LYLICH_VIENCHUC (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MADANHHIEU CHAR(5),
    IN p_MATONGIAO CHAR(5),
    IN p_MAHOCHAM CHAR(5),
    IN p_MATRINHDO CHAR(5),
    IN p_MADANTOC CHAR(5),
    IN p_MAHANGTHUONGBINH CHAR(5),
    IN p_MAXAPHUONG CHAR(5),
    IN p_XAP_MAXAPHUONG CHAR(5),
    IN p_HO VARCHAR(20),
    IN p_TENLOT VARCHAR(40),
    IN p_TEN VARCHAR(20),
    IN p_TENKHAC VARCHAR(100),
    IN p_NGAYSINH DATETIME,
    IN p_GIOITINH VARCHAR(3),
    IN p_NGAYTUYENDUNG DATETIME,
    IN p_SOHIEUVIENCHUC CHAR(10),
    IN p_ANHDAIDIEN TEXT,
    IN p_SOCCCD CHAR(10),
    IN p_NOICAPCCCD CHAR(100),
    IN p_NGAYCAPCCCD DATETIME,
    IN p_SOBAOHIEM CHAR(10),
    IN p_NHOMMAU CHAR(3),
    IN p_NAMDUOCPHONGHOCHAM DATETIME,
    IN p_NAMDUOCPHONGDANHHIEU DATETIME
)
BEGIN
    INSERT INTO VIENCHUC (
        MAVIENCHUC, MADANHHIEU, MATONGIAO, MAHOCHAM, MATRINHDO, MADANTOC, 
        MAHANGTHUONGBINH, MAXAPHUONG, XAP_MAXAPHUONG, HO, TENLOT, TEN, 
        TENKHAC, NGAYSINH, GIOITINH, NGAYTUYENDUNG, SOHIEUVIENCHUC, 
        ANHDAIDIEN, SOCCCD, NOICAPCCCD, NGAYCAPCCCD, SOBAOHIEM, NHOMMAU, 
        NAMDUOCPHONGHOCHAM, NAMDUOCPHONGDANHHIEU
    ) 
    VALUES (
        p_MAVIENCHUC, p_MADANHHIEU, p_MATONGIAO, p_MAHOCHAM, p_MATRINHDO, p_MADANTOC, 
        p_MAHANGTHUONGBINH, p_MAXAPHUONG, p_XAP_MAXAPHUONG, p_HO, p_TENLOT, p_TEN, 
        p_TENKHAC, p_NGAYSINH, p_GIOITINH, p_NGAYTUYENDUNG, p_SOHIEUVIENCHUC, 
        p_ANHDAIDIEN, p_SOCCCD, p_NOICAPCCCD, p_NGAYCAPCCCD, p_SOBAOHIEM, p_NHOMMAU, 
        p_NAMDUOCPHONGHOCHAM, p_NAMDUOCPHONGDANHHIEU
    )
    ON DUPLICATE KEY UPDATE
        MADANHHIEU = p_MADANHHIEU,
        MATONGIAO = p_MATONGIAO,
        MAHOCHAM = p_MAHOCHAM,
        MATRINHDO = p_MATRINHDO,
        MADANTOC = p_MADANTOC,
        MAHANGTHUONGBINH = p_MAHANGTHUONGBINH,
        MAXAPHUONG = p_MAXAPHUONG,
        XAP_MAXAPHUONG = p_XAP_MAXAPHUONG,
        HO = p_HO,
        TENLOT = p_TENLOT,
        TEN = p_TEN,
        TENKHAC = p_TENKHAC,
        NGAYSINH = p_NGAYSINH,
        GIOITINH = p_GIOITINH,
        NGAYTUYENDUNG = p_NGAYTUYENDUNG,
        SOHIEUVIENCHUC = p_SOHIEUVIENCHUC,
        ANHDAIDIEN = p_ANHDAIDIEN,
        SOCCCD = p_SOCCCD,
        NOICAPCCCD = p_NOICAPCCCD,
        NGAYCAPCCCD = p_NGAYCAPCCCD,
        SOBAOHIEM = p_SOBAOHIEM,
        NHOMMAU = p_NHOMMAU,
        NAMDUOCPHONGHOCHAM = p_NAMDUOCPHONGHOCHAM,
        NAMDUOCPHONGDANHHIEU = p_NAMDUOCPHONGDANHHIEU;
END$$

DELIMITER ;


DELIMITER $$


CREATE PROCEDURE SP_CAPNHAT_LUONG_VIENCHUC (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MACHITIETLUONG CHAR(5),
    IN p_THOIGIANBATDAUHUONG DATETIME
)
BEGIN
    INSERT INTO THUOC_NHOM_NGACH (MAVIENCHUC, MACHITIETLUONG, THOIGIANBATDAUHUONG)
    VALUES (p_MAVIENCHUC, p_MACHITIETLUONG, p_THOIGIANBATDAUHUONG)
    ON DUPLICATE KEY UPDATE
        MACHITIETLUONG = p_MACHITIETLUONG,
        THOIGIANBATDAUHUONG = p_THOIGIANBATDAUHUONG;
END$$

DELIMITER ;

DELIMITER $$



CREATE PROCEDURE SP_CAPNHAT_KHENTHUONG_VIENCHUC (
    IN p_MAHINHTHUCKHENTHUONG CHAR(5),
    IN p_MAVIENCHUC CHAR(10),
    IN p_NAMNHANKHENTHUONG DATETIME,
    IN p_SOQUYETDINHKHENTHUONG CHAR(50),
    IN p_NGUOIKYQUYETDINHKHENTHUONG CHAR(150)
)
BEGIN
    INSERT INTO DUOC_KHENTHUONG (
        MAHINHTHUCKHENTHUONG, MAVIENCHUC, NAMNHANKHENTHUONG, 
        SOQUYETDINHKHENTHUONG, NGUOIKYQUYETDINHKHENTHUONG
    )
    VALUES (
        p_MAHINHTHUCKHENTHUONG, p_MAVIENCHUC, p_NAMNHANKHENTHUONG, 
        p_SOQUYETDINHKHENTHUONG, p_NGUOIKYQUYETDINHKHENTHUONG
    )
    ON DUPLICATE KEY UPDATE
        NAMNHANKHENTHUONG = p_NAMNHANKHENTHUONG,
        SOQUYETDINHKHENTHUONG = p_SOQUYETDINHKHENTHUONG,
        NGUOIKYQUYETDINHKHENTHUONG = p_NGUOIKYQUYETDINHKHENTHUONG;
END$$

DELIMITER ;


DELIMITER $$



CREATE PROCEDURE SP_CAPNHAT_KYLUAT_VIENCHUC (
    IN p_MAHINHTHUCKYLUAT CHAR(5),
    IN p_MAVIENCHUC CHAR(10),
    IN p_NAMBIKYLUAT DATETIME,
    IN p_SOQUYETDINHKYLUAT CHAR(50),
    IN p_NGUOIKYQUYETDINHKYLUAT CHAR(150)
)
BEGIN
    INSERT INTO BI_KYLUAT (
        MAHINHTHUCKYLUAT, MAVIENCHUC, NAMBIKYLUAT, 
        SOQUYETDINHKYLUAT, NGUOIKYQUYETDINHKYLUAT
    )
    VALUES (
        p_MAHINHTHUCKYLUAT, p_MAVIENCHUC, p_NAMBIKYLUAT, 
        p_SOQUYETDINHKYLUAT, p_NGUOIKYQUYETDINHKYLUAT
    )
    ON DUPLICATE KEY UPDATE
        NAMBIKYLUAT = p_NAMBIKYLUAT,
        SOQUYETDINHKYLUAT = p_SOQUYETDINHKYLUAT,
        NGUOIKYQUYETDINHKYLUAT = p_NGUOIKYQUYETDINHKYLUAT;
END$$

DELIMITER ;


DELIMITER $$

CREATE PROCEDURE SP_LAY_DS_VIENCHUC_THEO_COQUAN (
    IN p_MACOQUAN CHAR(5)
)
BEGIN
    SELECT
        vc.MAVIENCHUC,
        CONCAT(
            IFNULL(vc.HO, ''),
            ' ',
            IFNULL(vc.TENLOT, ''),
            ' ',
            IFNULL(vc.TEN, '')
        ) AS HOTEN,

        vc.NGAYSINH,
        vc.GIOITINH,
        vc.SOCCCD,
        vc.SOBAOHIEM,

        dt.TENDANTOC,
        tg.TENTONGIAO,

        tdhv.TRINHDOGIAODUCPHOTHONG,
        tdhv.TRINHDONGHIEPVUCHUYENNGANH,

        hh.TENHOCHAM,
        dh.TENDANHHIEU,

        cq.MACOQUAN,
        cq.TENCOQUAN,

        td.NGAYTUYENDUNG

    FROM TUYENDUNG td

    INNER JOIN VIENCHUC vc
        ON td.MAVIENCHUC = vc.MAVIENCHUC

    INNER JOIN COQUAN cq
        ON td.MACOQUAN = cq.MACOQUAN

    LEFT JOIN DANTOC dt
        ON vc.MADANTOC = dt.MADANTOC

    LEFT JOIN TONGIAO tg
        ON vc.MATONGIAO = tg.MATONGIAO

    LEFT JOIN TRINHDOHOCVAN tdhv
        ON vc.MATRINHDO = tdhv.MATRINHDO

    LEFT JOIN HOCHAM hh
        ON vc.MAHOCHAM = hh.MAHOCHAM

    LEFT JOIN DANHHIEU dh
        ON vc.MADANHHIEU = dh.MADANHHIEU

    WHERE td.MACOQUAN = p_MACOQUAN;

END$$

DELIMITER ;