DELIMITER $$

CREATE PROCEDURE SP_THEM_USERS (
    IN p_mavienchuc CHAR(10),
    IN p_role VARCHAR(20)
)
BEGIN
    DECLARE db_role VARCHAR(30);

    IF p_role = 'admin' THEN
        SET db_role = 'admin_role';
    ELSEIF p_role = 'hr' THEN
        SET db_role = 'hr_role';
    ELSEIF p_role = 'manager' THEN
        SET db_role = 'manager_role';
    ELSE
        SET db_role = 'viewer_role';
    END IF;

    INSERT INTO USERS (MAVIENCHUC, PASSWORD, ROLE)
    VALUES (p_mavienchuc, p_mavienchuc, p_role);

    -- Create user
    SET @sql = CONCAT("CREATE USER '", p_mavienchuc, "'@'%' IDENTIFIED BY '", p_mavienchuc, "'");
    PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

    -- Assign role
    SET @sql2 = CONCAT("GRANT '", db_role, "' TO '", p_mavienchuc, "'@'%'");
    PREPARE stmt2 FROM @sql2; EXECUTE stmt2; DEALLOCATE PREPARE stmt2;
    
    -- Set default role
    SET @sql3 = CONCAT("SET DEFAULT ROLE '", db_role, "' TO '", p_mavienchuc, "'@'%'");
    PREPARE stmt3 FROM @sql3; EXECUTE stmt3; DEALLOCATE PREPARE stmt3;
END$$

DELIMITER ;


DELIMITER $$
CREATE PROCEDURE SP_THEM_VIENCHUC (
    IN p_MAVIENCHUC CHAR(10), IN p_MADANHHIEU CHAR(5), IN p_MATONGIAO CHAR(5),
    IN p_MAHOCHAM CHAR(5), IN p_MATRINHDO CHAR(5), IN p_MADANTOC CHAR(5),
    IN p_MAHANGTHUONGBINH CHAR(5), IN p_MAXAPHUONG CHAR(5), IN p_XAP_MAXAPHUONG CHAR(5),
    IN p_HO VARCHAR(20), IN p_TENLOT VARCHAR(40), IN p_TEN VARCHAR(20), IN p_TENKHAC VARCHAR(100),
    IN p_NGAYSINH DATETIME, IN p_GIOITINH VARCHAR(3), IN p_NGAYTUYENDUNG DATETIME,
    IN p_SOHIEUVIENCHUC CHAR(10), IN p_ANHDAIDIEN TEXT, IN p_SOCCCD CHAR(10),
    IN p_NOICAPCCCD CHAR(100), IN p_NGAYCAPCCCD DATETIME, IN p_SOBAOHIEM CHAR(10),
    IN p_NHOMMAU CHAR(3), IN p_NAMDUOCPHONGHOCHAM DATETIME, IN p_NAMDUOCPHONGDANHHIEU DATETIME,
    IN p_role VARCHAR(20)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    START TRANSACTION;

    INSERT INTO VIENCHUC (
        MAVIENCHUC, MADANHHIEU, MATONGIAO, MAHOCHAM, MATRINHDO, MADANTOC, 
        MAHANGTHUONGBINH, MAXAPHUONG, XAP_MAXAPHUONG, HO, TENLOT, TEN, 
        TENKHAC, NGAYSINH, GIOITINH, NGAYTUYENDUNG, SOHIEUVIENCHUC, 
        ANHDAIDIEN, SOCCCD, NOICAPCCCD, NGAYCAPCCCD, SOBAOHIEM, NHOMMAU, 
        NAMDUOCPHONGHOCHAM, NAMDUOCPHONGDANHHIEU
    ) 
    VALUES (
        p_MAVIENCHUC, p_MADANHHIEU, p_MATONGIAO, p_MAHOCHAM, p_MATRINHDO, p_MADANTOC, 
        p_MAHANGTHUONGBINH, p_MAXAPHUONG, p_XAP_MAXAPHUONG, p_HO, p_TENLOT, p_TEN, 
        p_TENKHAC, p_NGAYSINH, p_GIOITINH, p_NGAYTUYENDUNG, p_SOHIEUVIENCHUC, 
        p_ANHDAIDIEN, p_SOCCCD, p_NOICAPCCCD, p_NGAYCAPCCCD, p_SOBAOHIEM, p_NHOMMAU, 
        p_NAMDUOCPHONGHOCHAM, p_NAMDUOCPHONGDANHHIEU
    );

    CALL SP_THEM_USERS(p_MAVIENCHUC, p_role);

    COMMIT;
END$$

DELIMITER ;


DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_USERS (
    IN p_mavienchuc CHAR(10),
    IN p_role VARCHAR(20)
)
BEGIN
    DECLARE old_role VARCHAR(20);
    DECLARE old_db_role VARCHAR(30);
    DECLARE new_db_role VARCHAR(30);

    SELECT ROLE INTO old_role FROM USERS WHERE MAVIENCHUC = p_mavienchuc;

    --  old role
    IF old_role = 'admin' THEN SET old_db_role = 'admin_role';
    ELSEIF old_role = 'hr' THEN SET old_db_role = 'hr_role';
    ELSEIF old_role = 'manager' THEN SET old_db_role = 'manager_role';
    ELSE SET old_db_role = 'viewer_role';
    END IF;

    -- new role
    IF p_role = 'admin' THEN SET new_db_role = 'admin_role';
    ELSEIF p_role = 'hr' THEN SET new_db_role = 'hr_role';
    ELSEIF p_role = 'manager' THEN SET new_db_role = 'manager_role';
    ELSE SET new_db_role = 'viewer_role';
    END IF;

    -- update system
    UPDATE USERS SET ROLE = p_role WHERE MAVIENCHUC = p_mavienchuc;


    IF old_db_role <> new_db_role THEN
        SET @sql_revoke = CONCAT("REVOKE '", old_db_role, "' FROM '", p_mavienchuc, "'@'%'");
        PREPARE stmt_rev FROM @sql_revoke; EXECUTE stmt_rev; DEALLOCATE PREPARE stmt_rev;

        SET @sql_grant = CONCAT("GRANT '", new_db_role, "' TO '", p_mavienchuc, "'@'%'");
        PREPARE stmt_gnt FROM @sql_grant; EXECUTE stmt_gnt; DEALLOCATE PREPARE stmt_gnt;

        SET @sql_def = CONCAT("SET DEFAULT ROLE '", new_db_role, "' TO '", p_mavienchuc, "'@'%'");
        PREPARE stmt_def FROM @sql_def; EXECUTE stmt_def; DEALLOCATE PREPARE stmt_def;
    END IF;
END$$
DELIMITER ;
DELIMITER $$
CREATE PROCEDURE SP_CAPNHAT_VIENCHUC (
    IN p_MAVIENCHUC CHAR(10), IN p_MADANHHIEU CHAR(5), IN p_MATONGIAO CHAR(5),
    IN p_MAHOCHAM CHAR(5), IN p_MATRINHDO CHAR(5), IN p_MADANTOC CHAR(5),
    IN p_MAHANGTHUONGBINH CHAR(5), IN p_MAXAPHUONG CHAR(5), IN p_XAP_MAXAPHUONG CHAR(5),
    IN p_HO VARCHAR(20), IN p_TENLOT VARCHAR(40), IN p_TEN VARCHAR(20), IN p_TENKHAC VARCHAR(100),
    IN p_NGAYSINH DATETIME, IN p_GIOITINH VARCHAR(3), IN p_NGAYTUYENDUNG DATETIME,
    IN p_SOHIEUVIENCHUC CHAR(10), IN p_ANHDAIDIEN TEXT, IN p_SOCCCD CHAR(10),
    IN p_NOICAPCCCD CHAR(100), IN p_NGAYCAPCCCD DATETIME, IN p_SOBAOHIEM CHAR(10),
    IN p_NHOMMAU CHAR(3), IN p_NAMDUOCPHONGHOCHAM DATETIME, IN p_NAMDUOCPHONGDANHHIEU DATETIME,
    IN p_role VARCHAR(20)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    START TRANSACTION;

    UPDATE VIENCHUC SET
        MADANHHIEU = p_MADANHHIEU, MATONGIAO = p_MATONGIAO, MAHOCHAM = p_MAHOCHAM,
        MATRINHDO = p_MATRINHDO, MADANTOC = p_MADANTOC, MAHANGTHUONGBINH = p_MAHANGTHUONGBINH,
        MAXAPHUONG = p_MAXAPHUONG, XAP_MAXAPHUONG = p_XAP_MAXAPHUONG, HO = p_HO,
        TENLOT = p_TENLOT, TEN = p_TEN, TENKHAC = p_TENKHAC, NGAYSINH = p_NGAYSINH,
        GIOITINH = p_GIOITINH, NGAYTUYENDUNG = p_NGAYTUYENDUNG, SOHIEUVIENCHUC = p_SOHIEUVIENCHUC,
        ANHDAIDIEN = p_ANHDAIDIEN, SOCCCD = p_SOCCCD, NOICAPCCCD = p_NOICAPCCCD,
        NGAYCAPCCCD = p_NGAYCAPCCCD, SOBAOHIEM = p_SOBAOHIEM, NHOMMAU = p_NHOMMAU,
        NAMDUOCPHONGHOCHAM = p_NAMDUOCPHONGHOCHAM, NAMDUOCPHONGDANHHIEU = p_NAMDUOCPHONGDANHHIEU
    WHERE MAVIENCHUC = p_MAVIENCHUC;

    CALL SP_CAPNHAT_USERS(p_MAVIENCHUC, p_role);

    COMMIT;
END$$

DELIMITER ;



DELIMITER $$

#               Lương

CREATE PROCEDURE SP_CAPNHAT_LUONG_VIENCHUC (
    IN p_MAVIENCHUC CHAR(10),
    IN p_MACHITIETLUONG CHAR(5),
    IN p_THOIGIANBATDAUHUONG DATETIME
)
BEGIN
    INSERT INTO THUOC_NHOM_NGACH (MAVIENCHUC, MACHITIETLUONG, THOIGIANBATDAUHUONG)
    VALUES (p_MAVIENCHUC, p_MACHITIETLUONG, p_THOIGIANBATDAUHUONG)
    ON DUPLICATE KEY UPDATE
        MACHITIETLUONG = p_MACHITIETLUONG,
        THOIGIANBATDAUHUONG = p_THOIGIANBATDAUHUONG;
END$$

DELIMITER ;


--    KHEN THUONG
DELIMITER $$



CREATE PROCEDURE SP_CAPNHAT_KHENTHUONG_VIENCHUC (
    IN p_MAHINHTHUCKHENTHUONG CHAR(5),
    IN p_MAVIENCHUC CHAR(10),
    IN p_NAMNHANKHENTHUONG DATETIME,
    IN p_SOQUYETDINHKHENTHUONG CHAR(50),
    IN p_NGUOIKYQUYETDINHKHENTHUONG CHAR(150)
)
BEGIN
    INSERT INTO DUOC_KHENTHUONG (
        MAHINHTHUCKHENTHUONG, MAVIENCHUC, NAMNHANKHENTHUONG, 
        SOQUYETDINHKHENTHUONG, NGUOIKYQUYETDINHKHENTHUONG
    )
    VALUES (
        p_MAHINHTHUCKHENTHUONG, p_MAVIENCHUC, p_NAMNHANKHENTHUONG, 
        p_SOQUYETDINHKHENTHUONG, p_NGUOIKYQUYETDINHKHENTHUONG
    )
    ON DUPLICATE KEY UPDATE
        NAMNHANKHENTHUONG = p_NAMNHANKHENTHUONG,
        SOQUYETDINHKHENTHUONG = p_SOQUYETDINHKHENTHUONG,
        NGUOIKYQUYETDINHKHENTHUONG = p_NGUOIKYQUYETDINHKHENTHUONG;
END$$

DELIMITER ;


DELIMITER $$
CREATE PROCEDURE SP_XOA_KHENTHUONG_VIENCHUC (
    IN p_MAHINHTHUCKHENTHUONG CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    DELETE FROM DUOC_KHENTHUONG
    WHERE MAHINHTHUCKHENTHUONG = p_MAHINHTHUCKHENTHUONG AND MAVIENCHUC = p_MAVIENCHUC;
END$$
DELiMITER ;



--                Kỷluật
DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_KYLUAT_VIENCHUC (
    IN p_MAHINHTHUCKYLUAT CHAR(5),
    IN p_MAVIENCHUC CHAR(10),
    IN p_NAMBIKYLUAT DATETIME,
    IN p_SOQUYETDINHKYLUAT CHAR(50),
    IN p_NGUOIKYQUYETDINHKYLUAT CHAR(150)
)
BEGIN
    INSERT INTO BI_KYLUAT (
        MAHINHTHUCKYLUAT, MAVIENCHUC, NAMBIKYLUAT, 
        SOQUYETDINHKYLUAT, NGUOIKYQUYETDINHKYLUAT
    )
    VALUES (
        p_MAHINHTHUCKYLUAT, p_MAVIENCHUC, p_NAMBIKYLUAT, 
        p_SOQUYETDINHKYLUAT, p_NGUOIKYQUYETDINHKYLUAT
    )
    ON DUPLICATE KEY UPDATE
        NAMBIKYLUAT = p_NAMBIKYLUAT,
        SOQUYETDINHKYLUAT = p_SOQUYETDINHKYLUAT,
        NGUOIKYQUYETDINHKYLUAT = p_NGUOIKYQUYETDINHKYLUAT;
END$$

DELIMITER ;

DELIMITER $$

CREATE PROCEDURE SP_XOA_KYLUAT_VIENCHUC (
    IN p_MAHINHTHUCKYLUAT CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    DELETE FROM BI_KYLUAT
    WHERE MAHINHTHUCKYLUAT = p_MAHINHTHUCKYLUAT AND MAVIENCHUC = p_MAVIENCHUC;
END$$
DELiMITER ;

--  COS Cấp luận chính trị

DELIMITER $$

CREATE PROCEDURE SP_CAPNHAT_CO_CAPLYLUANCHINHTRI (
    IN p_MACAPCT CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    INSERT INTO CO_CAPLYLUANCHINHTRI (MACAPCT, MAVIENCHUC)
    VALUES (p_MACAPCT, p_MAVIENCHUC)
    ON DUPLICATE KEY UPDATE MACAPCT = p_MACAPCT;
END$$

CREATE PROCEDURE SP_XOA_CO_CAPLYLUANCHINHTRI (
    IN p_MACAPCT CHAR(5),
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    DELETE FROM CO_CAPLYLUANCHINHTRI 
    WHERE MACAPCT = p_MACAPCT AND MAVIENCHUC = p_MAVIENCHUC;
END$$

DELIMITER ;





