DELIMITER $$

CREATE PROCEDURE SP_CANHAN_THONGTIN(
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    SELECT *
    FROM VW_LAY_DS_VIENCHUC
    WHERE MAVIENCHUC = p_MAVIENCHUC;
END $$

DELIMITER ;


DELIMITER $$

CREATE PROCEDURE SP_CANHAN_CONGTAC(
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    SELECT *
    FROM VW_DS_CONGTAC
    WHERE MAVIENCHUC = p_MAVIENCHUC
    ORDER BY THOIGIANGIUCHUCVU DESC;
END $$

DELIMITER ;


DELIMITER $$

CREATE PROCEDURE SP_CANHAN_KHENTHUONG(
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    SELECT
        ht.TENHINHTHUCKHENTHUONG,
        dk.NAMNHANKHENTHUONG,
        dk.SOQUYETDINHKHENTHUONG,
        dk.NGUOIKYQUYETDINHKHENTHUONG
    FROM DUOC_KHENTHUONG dk
    JOIN HINHTHUCKHENTHUONG ht
        ON dk.MAHINHTHUCKHENTHUONG = ht.MAHINHTHUCKHENTHUONG
    WHERE dk.MAVIENCHUC = p_MAVIENCHUC
    ORDER BY dk.NAMNHANKHENTHUONG DESC;
END $$

DELIMITER ;


DELIMITER $$

CREATE PROCEDURE SP_CANHAN_KYLUAT(
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    SELECT
        kl.TENHINHTHUCKYLUAT,
        bk.NAMBIKYLUAT,
        bk.SOQUYETDINHKYLUAT,
        bk.NGUOIKYQUYETDINHKYLUAT
    FROM BI_KYLUAT bk
    JOIN HINHTHUCKYLUAT kl
        ON bk.MAHINHTHUCKYLUAT = kl.MAHINHTHUCKYLUAT
    WHERE bk.MAVIENCHUC = p_MAVIENCHUC
    ORDER BY bk.NAMBIKYLUAT DESC;
END $$

DELIMITER ;



DELIMITER $$

CREATE PROCEDURE SP_CANHAN_TRINHDO(
    IN p_MAVIENCHUC CHAR(10)
)
BEGIN
    SELECT
        cm.TENCHUYENMON,
        nn.TENNGOAINGU,
        th.CHUNGCHITINHOC
    FROM VIENCHUC vc

    LEFT JOIN CO_TRDCM_CAONHAT ctcm
        ON vc.MAVIENCHUC = ctcm.MAVIENCHUC
    LEFT JOIN CHUYENMON cm
        ON ctcm.MACHUYENMON = cm.MACHUYENMON

    LEFT JOIN CO_TRD_NGOAINGU ctng
        ON vc.MAVIENCHUC = ctng.MAVIENCHUC
    LEFT JOIN NGOAINGU nn
        ON ctng.MANGOAINGU = nn.MANGOAINGU

    LEFT JOIN CO_TRD_TINHOC ctth
        ON vc.MAVIENCHUC = ctth.MAVIENCHUC
    LEFT JOIN CHUNGCHITINHOC th
        ON ctth.MACHUNGCHITINHOC = th.MACHUNGCHITINHOC

    WHERE vc.MAVIENCHUC = p_MAVIENCHUC;
END $$

DELIMITER ;


