DELIMITER $$

CREATE PROCEDURE SP_LAY_VIENCHUC_THEO_MA(
    IN p_MAVIENCHUC VARCHAR(20)
)
BEGIN
    SELECT
        MAVIENCHUC,
        HOTEN,
        NGAYSINH,
        GIOITINH,
        TENDANTOC,
        TENTONGIAO,
        TRINHDONGHIEPVUCHUYENNGANH,
        TENCOQUAN,
        TENCHUCVU
    FROM VW_LAY_DS_VIENCHUC
    WHERE MAVIENCHUC = p_MAVIENCHUC;
END $$

DELIMITER ;